In [1]:
import pandas as pd
import numpy as np

In [2]:
pop = pd.read_csv('data\FAOSTAT_Population_2017_2020.csv')
alim = pd.read_csv('data\FAOSTAT_DisponibiliteAlimentaire_2017-2020.csv')
stabilite = pd.read_csv('data\FAOSTAT_Stabilité_politique.csv')
pib = pd.read_csv('data\FAOSTAT_data_Pib_habitants.csv')
prodVolail = pd.read_csv('data\FAOSTAT_Production_Volailles.csv')

In [3]:
annee = 2020

# Nettoyage des Données

In [4]:
pop

,Code Domaine,Domaine,Code zone (M49),Zone,Code Élément,Élément,Code Produit (CPC),Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
0,FBS,Bilans Alimentaires (2010-),4,Afghanistan,511,Population totale,S2501,Population,2017,2017,1000 personnes,36296.00,X,Ciffre de sources internationales
1,FBS,Bilans Alimentaires (2010-),4,Afghanistan,511,Population totale,S2501,Population,2018,2018,1000 personnes,37172.00,X,Ciffre de sources internationales
2,FBS,Bilans Alimentaires (2010-),4,Afghanistan,511,Population totale,S2501,Population,2019,2019,1000 personnes,38041.75,X,Ciffre de sources internationales
3,FBS,Bilans Alimentaires (2010-),4,Afghanistan,511,Population totale,S2501,Population,2020,2020,1000 personnes,38928.35,X,Ciffre de sources internationales
4,FBS,Bilans Alimentaires (2010-),710,Afrique du Sud,511,Population totale,S2501,Population,2017,2017,1000 personnes,57010.00,X,Ciffre de sources internationales
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
727,FBS,Bilans Alimentaires (2010-),894,Zambie,511,Population totale,S2501,Population,2020,2020,1000 personnes,18383.96,X,Ciffre de sources internationales
728,FBS,Bilans Alimentaires (2010-),716,Zimbabwe,511,Population totale,S2501,Population,2017,2017,1000 personnes,14236.59,X,Ciffre de sources internationales
729,FBS,Bilans Alimentaires (2010-),716,Zimbabwe,511,Population totale,S2501,Population,2018,2018,1000 personnes,14438.80,X,Ciffre de sources internationales
730,FBS,Bilans Alimentaires (2010-),716,Zimbabwe,511,Population totale,S2501,Population,2019,2019,1000 personnes,14645.47,X,Ciffre de sources internationales
731,FBS,Bilans Alimentaires (2010-),716,Zimbabwe,511,Population totale,S2501,Population,2020,2020,1000 personnes,14862.92,X,Ciffre de sources internationales

In [5]:
pop.describe(include='all')

,Code Domaine,Domaine,Code zone (M49),Zone,Code Élément,Élément,Code Produit (CPC),Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
count,732,732,732.000000,732,732.0,732,732,732,732.000000,732.000000,732,7.320000e+02,732,732
unique,1,1,NaN,186,NaN,1,1,1,NaN,NaN,1,NaN,1,1
top,FBS,Bilans Alimentaires (2010-),NaN,Afghanistan,NaN,Population totale,S2501,Population,NaN,NaN,1000 personnes,NaN,X,Ciffre de sources internationales
freq,732,732,NaN,4,NaN,732,732,732,NaN,NaN,732,NaN,732,732
mean,NaN,NaN,425.740437,NaN,511.0,NaN,NaN,NaN,2018.516393,2018.516393,NaN,4.963196e+04,NaN,NaN
std,NaN,NaN,251.145689,NaN,0.0,NaN,NaN,NaN,1.118678,1.118678,NaN,1.829714e+05,NaN,NaN
min,NaN,NaN,4.000000,NaN,511.0,NaN,NaN,NaN,2017.000000,2017.000000,NaN,1.076000e+01,NaN,NaN
25%,NaN,NaN,204.000000,NaN,511.0,NaN,NaN,NaN,2018.000000,2018.000000,NaN,2.529315e+03,NaN,NaN
50%,NaN,NaN,418.000000,NaN,511.0,NaN,NaN,NaN,2019.000000,2019.000000,NaN,9.738060e+03,NaN,NaN
75%,NaN,NaN,642.000000,NaN,511.0,NaN,NaN,NaN,2020.000000,2020.000000,NaN,3.108095e+04,NaN,NaN
max,NaN,NaN,894.000000,NaN,511.0,NaN,NaN,NaN,2020.000000,2020.000000,NaN,1.471287e+06,NaN,NaN

On commence par enlever les colonnes qui ne nous servent pas, à savoir tout sauf l'année, le pays et le nombre d'habitants qu'on prend soin de multiplier par 1000 afin d'obtenir le nombre exact d'habitants.

In [6]:
pop = pop[['Zone', 'Année', 'Valeur']]
pop['Valeur'] = pop['Valeur']*1000
pop = pop.rename(columns={'Zone': 'Pays',
                          'Valeur': 'Population'})

C:\Users\thebe\AppData\Local\Temp\ipykernel_8636\1716358708.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pop['Valeur'] = pop['Valeur']*1000

On ajoute une colonne qui servira de clé primaire

In [7]:
pop['id'] = pop['Pays'] + "/" + pop['Année'].astype('str')

In [8]:
pop

               Pays  Année  Population                   id
0       Afghanistan   2017  36296000.0     Afghanistan/2017
1       Afghanistan   2018  37172000.0     Afghanistan/2018
2       Afghanistan   2019  38041750.0     Afghanistan/2019
3       Afghanistan   2020  38928350.0     Afghanistan/2020
4    Afrique du Sud   2017  57010000.0  Afrique du Sud/2017
..              ...    ...         ...                  ...
727          Zambie   2020  18383960.0          Zambie/2020
728        Zimbabwe   2017  14236590.0        Zimbabwe/2017
729        Zimbabwe   2018  14438800.0        Zimbabwe/2018
730        Zimbabwe   2019  14645470.0        Zimbabwe/2019
731        Zimbabwe   2020  14862920.0        Zimbabwe/2020

[732 rows x 4 columns]

On vérifie que la clé est bien unique

In [9]:
def EstPrimaire(df, id):
    if df[id].nunique() == len(df):
        print("La clé est bien unique")
    else:
        print("la clé n'est pas unique")


EstPrimaire(pop, 'id')

La clé est bien unique

On s'occupe de la table "stabilite" qui concerne la stabilité politique du pays

In [10]:
stabilite

,Code Domaine,Domaine,Code zone (M49),Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,FS,Données de la sécurité alimentaire,4,Afghanistan,6125,Valeur,21032,Stabilité politique et absence de violence/ter...,2000,2000,indice,-2.44,X,Ciffre de sources internationales,NaN
1,FS,Données de la sécurité alimentaire,4,Afghanistan,6125,Valeur,21032,Stabilité politique et absence de violence/ter...,2002,2002,indice,-2.04,X,Ciffre de sources internationales,NaN
2,FS,Données de la sécurité alimentaire,4,Afghanistan,6125,Valeur,21032,Stabilité politique et absence de violence/ter...,2003,2003,indice,-2.20,X,Ciffre de sources internationales,NaN
3,FS,Données de la sécurité alimentaire,4,Afghanistan,6125,Valeur,21032,Stabilité politique et absence de violence/ter...,2004,2004,indice,-2.30,X,Ciffre de sources internationales,NaN
4,FS,Données de la sécurité alimentaire,4,Afghanistan,6125,Valeur,21032,Stabilité politique et absence de violence/ter...,2005,2005,indice,-2.07,X,Ciffre de sources internationales,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3903,FS,Données de la sécurité alimentaire,716,Zimbabwe,6125,Valeur,21032,Stabilité politique et absence de violence/ter...,2016,2016,indice,-0.62,X,Ciffre de sources internationales,NaN
3904,FS,Données de la sécurité alimentaire,716,Zimbabwe,6125,Valeur,21032,Stabilité politique et absence de violence/ter...,2017,2017,indice,-0.71,X,Ciffre de sources internationales,NaN
3905,FS,Données de la sécurité alimentaire,716,Zimbabwe,6125,Valeur,21032,Stabilité politique et absence de violence/ter...,2018,2018,indice,-0.72,X,Ciffre de sources internationales,NaN
3906,FS,Données de la sécurité alimentaire,716,Zimbabwe,6125,Valeur,21032,Stabilité politique et absence de violence/ter...,2019,2019,indice,-0.96,X,Ciffre de sources internationales,NaN
3907,FS,Données de la sécurité alimentaire,716,Zimbabwe,6125,Valeur,21032,Stabilité politique et absence de violence/ter...,2020,2020,indice,-1.08,X,Ciffre de sources internationales,NaN

On ignore ce qui ne nous sert pas

In [11]:
stabilite = stabilite[['Zone', 'Année', 'Valeur']]

On crée une clé primaire comme précédemment

In [12]:
stabilite['id'] = stabilite['Zone']+"/" + stabilite['Année'].astype('str')
stabilite = stabilite.rename(columns={'Zone': 'Pays',
                                      'Valeur': 'Stabilité Politique'})
EstPrimaire(stabilite, 'id')

La clé est bien unique

C:\Users\thebe\AppData\Local\Temp\ipykernel_8636\3708130892.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stabilite['id'] = stabilite['Zone']+"/" + stabilite['Année'].astype('str')

In [13]:
stabilite.describe()

             Année  Stabilité Politique
count  3908.000000          3908.000000
mean   2010.542733            -0.050000
std       5.827217             0.997415
min    2000.000000            -3.310000
25%    2006.000000            -0.710000
50%    2011.000000             0.055000
75%    2016.000000             0.800000
max    2020.000000             1.970000

On s'occupe de la table pib qui contient le pib par habitant

In [14]:
pib.describe(include='all')

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
count,2533,2533,2533.000000,2533,2533.0,2533,2533.0,2533,2533.000000,2533.000000,2533,2533.000000,2533,2533,0.0
unique,1,1,NaN,232,NaN,1,NaN,1,NaN,NaN,1,NaN,1,1,NaN
top,FS,Données de la sécurité alimentaire,NaN,Myanmar,NaN,Valeur,NaN,"PIB par habitant, ($ PPA internationaux consta...",NaN,NaN,I$,NaN,X,Ciffre de sources internationales,NaN
freq,2533,2533,NaN,11,NaN,2533,NaN,2533,NaN,NaN,2533,NaN,2533,2533,NaN
mean,NaN,NaN,1147.318595,NaN,6126.0,NaN,22013.0,NaN,2015.003948,2015.003948,NaN,19464.324872,NaN,NaN,NaN
std,NaN,NaN,2149.175706,NaN,0.0,NaN,0.0,NaN,5.442358,5.442358,NaN,20625.032001,NaN,NaN,NaN
min,NaN,NaN,1.000000,NaN,6126.0,NaN,22013.0,NaN,2000.000000,2000.000000,NaN,630.700000,NaN,NaN,NaN
25%,NaN,NaN,84.000000,NaN,6126.0,NaN,22013.0,NaN,2013.000000,2013.000000,NaN,4527.700000,NaN,NaN,NaN
50%,NaN,NaN,156.000000,NaN,6126.0,NaN,22013.0,NaN,2016.000000,2016.000000,NaN,12357.900000,NaN,NaN,NaN
75%,NaN,NaN,235.000000,NaN,6126.0,NaN,22013.0,NaN,2019.000000,2019.000000,NaN,27797.100000,NaN,NaN,NaN
max,NaN,NaN,9011.000000,NaN,6126.0,NaN,22013.0,NaN,2021.000000,2021.000000,NaN,161972.000000,NaN,NaN,NaN

In [15]:
pib = pib[['Zone', 'Année', 'Valeur']]
pib = pib.rename(columns={'Zone': 'Pays',
                          'Valeur': 'Pib/Habitant ($/habitant)'})

In [16]:
pib['id'] = pib['Pays'] + "/" + pib['Année'].astype('str')
EstPrimaire(pib, 'id')

La clé est bien unique

In [17]:
def checkUnusedId(dfToRmv, df2, id1, id2):
    listToRmv = dfToRmv[id1].tolist()
    listDf2 = df2[id2].tolist()
    tempo = []

    for i in listToRmv:
        if i in listDf2:
            tempo.append(i)
    for i in tempo:
        listToRmv.remove(i)

    if len(listToRmv) != 0:
        listToRmvUnique = pd.Series(listToRmv).unique()
        print(len(listToRmvUnique), id1, "non utilisé(s) (",
              len(listToRmv), ") :", listToRmvUnique)
    else:
        print("Auncun", id1, "non utilisé")
    # dfToRmv = dfToRmv.drop(dfToRmv[dfToRmv[id1].isin(listToRmv)].index)

    return listToRmv

On s'occupe de la table ProdVollail

In [18]:
prodVolail

,Code Domaine,Domaine,Code zone (M49),Zone,Code Élément,Élément,Code Produit (CPC),Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
0,QCL,Cultures et produits animaux,4,Afghanistan,5112,Réserves,2151,Poulets,2018,2018,1000 têtes,14479.00,I,Valeur imputée
1,QCL,Cultures et produits animaux,4,Afghanistan,5112,Réserves,2151,Poulets,2019,2019,1000 têtes,13735.00,I,Valeur imputée
2,QCL,Cultures et produits animaux,4,Afghanistan,5112,Réserves,2151,Poulets,2020,2020,1000 têtes,13697.00,I,Valeur imputée
3,QCL,Cultures et produits animaux,4,Afghanistan,5510,Production,21121,"Viande, poulet, fraîche ou réfrigérée",2018,2018,tonnes,29434.79,I,Valeur imputée
4,QCL,Cultures et produits animaux,4,Afghanistan,5510,Production,21121,"Viande, poulet, fraîche ou réfrigérée",2019,2019,tonnes,27877.47,I,Valeur imputée
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1143,QCL,Cultures et produits animaux,716,Zimbabwe,5112,Réserves,2151,Poulets,2019,2019,1000 têtes,17000.00,E,Valeur estimée
1144,QCL,Cultures et produits animaux,716,Zimbabwe,5112,Réserves,2151,Poulets,2020,2020,1000 têtes,16200.00,E,Valeur estimée
1145,QCL,Cultures et produits animaux,716,Zimbabwe,5510,Production,21121,"Viande, poulet, fraîche ou réfrigérée",2018,2018,tonnes,103302.87,I,Valeur imputée
1146,QCL,Cultures et produits animaux,716,Zimbabwe,5510,Production,21121,"Viande, poulet, fraîche ou réfrigérée",2019,2019,tonnes,114344.00,A,Chiffre officiel
1147,QCL,Cultures et produits animaux,716,Zimbabwe,5510,Production,21121,"Viande, poulet, fraîche ou réfrigérée",2020,2020,tonnes,111546.00,A,Chiffre officiel

In [19]:
prodVolail = prodVolail.pivot_table(index=["Zone", "Année"], columns=[
                                    "Élément", "Unité", "Produit"], values="Valeur").droplevel(0, axis=1).droplevel(0, axis=1).reset_index()
prodVolail = prodVolail.rename(columns={"Zone": "Pays", "Poulets": "Milliers de poulets",
                               "Viande, poulet, fraîche ou réfrigérée": "Tonnes de viande de poulet produite"})

In [20]:
prodVolail

Produit,Pays,Année,Tonnes de viande de poulet produite,Milliers de poulets
0,Afghanistan,2018,29434.79,14479.0
1,Afghanistan,2019,27877.47,13735.0
2,Afghanistan,2020,27753.95,13697.0
3,Afrique du Sud,2018,1743285.00,173352.0
4,Afrique du Sud,2019,1814000.00,170252.0
...,...,...,...,...
582,Îles Cook,2019,16.45,18.0
583,Îles Cook,2020,15.88,17.0
584,Îles Salomon,2018,284.68,244.0
585,Îles Salomon,2019,283.99,245.0
586,Îles Salomon,2020,283.68,245.0

In [21]:
prodVolail.isna().mean()

Produit
Pays                                   0.000000
Année                                  0.000000
Tonnes de viande de poulet produite    0.001704
Milliers de poulets                    0.042589
dtype: float64

In [22]:
prodVolail[prodVolail["Tonnes de viande de poulet produite"].isna()][[
    'Pays', 'Année']]

Produit       Pays  Année
472      Slovaquie   2020

In [23]:
prodVolail = prodVolail.dropna(subset=['Tonnes de viande de poulet produite'])

In [24]:
prodVolail[prodVolail["Milliers de poulets"].isna()][['Pays', 'Année']]

Produit       Pays  Année
12       Allemagne   2018
13       Allemagne   2019
14       Allemagne   2020
33        Autriche   2018
34        Autriche   2019
35        Autriche   2020
77        Bulgarie   2020
122         Chypre   2020
146       Danemark   2020
153        Espagne   2018
154        Espagne   2019
155        Espagne   2020
187          Grèce   2019
188          Grèce   2020
228        Irlande   2018
229        Irlande   2019
230        Irlande   2020
237         Italie   2018
238         Italie   2019
239         Italie   2020
269       Lettonie   2020
300          Malte   2018
301          Malte   2019
302          Malte   2020
508       Tchéquie   2020

Étant donné qu'il manque les données des 3 années sur quasiment chaque pays de la liste, on va tout simplement les estimer à la médiane.

In [25]:
prodVolail["Milliers de poulets"] = prodVolail["Milliers de poulets"].fillna(
    prodVolail["Milliers de poulets"].median())

C:\Users\thebe\AppData\Local\Temp\ipykernel_8636\3484537884.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prodVolail["Milliers de poulets"] = prodVolail["Milliers de poulets"].fillna(

In [26]:
prodVolail['id'] = prodVolail['Pays'] + "/" + prodVolail['Année'].astype('str')
EstPrimaire(prodVolail, 'id')

La clé est bien unique

C:\Users\thebe\AppData\Local\Temp\ipykernel_8636\1966502645.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prodVolail['id'] = prodVolail['Pays'] + "/" + prodVolail['Année'].astype('str')

In [27]:
prodVolail.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 586 entries, 0 to 586
Data columns (total 5 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Pays                                 586 non-null    object
 1   Année                                586 non-null    int64
 2   Tonnes de viande de poulet produite  586 non-null    float64
 3   Milliers de poulets                  586 non-null    float64
 4   id                                   586 non-null    object
dtypes: float64(2), int64(1), object(2)
memory usage: 27.5+ KB

On s'occupe maintenant de la table "alim"

In [28]:
alim['Année'].unique()

array([2017, 2018, 2019, 2020], dtype=int64)

On crée une copie pour pouvoir revenir à ces données plus tard

In [29]:
alimOri = alim.copy()

In [30]:
alim

,Domaine,Zone,Élément,Produit,Année,Unité,Valeur
0,Bilans Alimentaires (2010-),Afghanistan,Importations - Quantité,Blé et produits,2017,Milliers de tonnes,3080.00
1,Bilans Alimentaires (2010-),Afghanistan,Importations - Quantité,Blé et produits,2018,Milliers de tonnes,3419.00
2,Bilans Alimentaires (2010-),Afghanistan,Importations - Quantité,Blé et produits,2019,Milliers de tonnes,2534.00
3,Bilans Alimentaires (2010-),Afghanistan,Importations - Quantité,Blé et produits,2020,Milliers de tonnes,2741.00
4,Bilans Alimentaires (2010-),Afghanistan,Exportations - Quantité,Blé et produits,2017,Milliers de tonnes,2.00
...,...,...,...,...,...,...,...
241475,Bilans Alimentaires (2010-),Zimbabwe,Disponibilité alimentaire (Kcal/personne/jour),Miscellanees,2020,Kcal/personne/jour,1.00
241476,Bilans Alimentaires (2010-),Zimbabwe,Disponibilité de protéines en quantité (g/pers...,Miscellanees,2017,g/personne/jour,0.03
241477,Bilans Alimentaires (2010-),Zimbabwe,Disponibilité de protéines en quantité (g/pers...,Miscellanees,2018,g/personne/jour,0.04
241478,Bilans Alimentaires (2010-),Zimbabwe,Disponibilité de protéines en quantité (g/pers...,Miscellanees,2019,g/personne/jour,0.09
241479,Bilans Alimentaires (2010-),Zimbabwe,Disponibilité de protéines en quantité (g/pers...,Miscellanees,2020,g/personne/jour,0.03

On ne garde que la colonne 'nourriture' qui correspond à l'utilisation liée à l'alimentation humaine

In [31]:
alim = alim[alim['Élément'].isin(['Disponibilité alimentaire (Kcal/personne/jour)',
                                 'Disponibilité de protéines en quantité (g/personne/jour)'])]

Retirons les colonnes inutiles

In [32]:
alim = alim[['Zone', 'Année', 'Élément', 'Valeur', 'Produit']]
alim = alim.rename(columns={'Zone': 'Pays'})

Créons maintenant un tableau contenant la part de la viande animale dans la consommation en Kcal et en gramme de protéines par personne

In [33]:
Viande_List = ['Viande de Bovins', "Viande d'Ovins/Caprins", 'Viande de porcins',
               'Viande de Suides', "Viande de Volailles", "Viande, Autre", "Abats Comestible"]

Calculons d'abord la consommation totale

In [34]:
part = alim.groupby(['Pays', 'Année', 'Élément'])['Valeur'].sum().reset_index(
).pivot_table('Valeur', ['Pays', 'Année'], 'Élément').reset_index()
part

Élément,Pays,Année,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité de protéines en quantité (g/personne/jour)
0,Afghanistan,2017,2303.0,59.51
1,Afghanistan,2018,2268.0,57.65
2,Afghanistan,2019,2237.0,56.06
3,Afghanistan,2020,2239.0,56.65
4,Afrique du Sud,2017,2896.0,79.68
...,...,...,...,...
727,Éthiopie,2020,2406.0,74.10
728,Îles Salomon,2017,2404.0,53.42
729,Îles Salomon,2018,2399.0,52.70
730,Îles Salomon,2019,2380.0,51.71
731,Îles Salomon,2020,2357.0,49.77

et maintenant la consommation de viande animale

In [35]:
alimViande = alim[alim['Produit'].isin(Viande_List)]
alimViande = alimViande.groupby(['Pays', 'Année', 'Élément'])['Valeur'].sum(
).reset_index().pivot_table('Valeur', ['Pays', 'Année'], 'Élément').reset_index()
alimViande = alimViande.rename(columns={'Disponibilité alimentaire (Kcal/personne/jour)': 'Disponibilité alimentaire (Viande) (Kcal/personne/jour)',
                                        'Disponibilité de protéines en quantité (g/personne/jour)': 'Disponibilité de protéines en quantité (Viande) (g/personne/jour)'})

In [36]:
part = pd.merge(part, alimViande, on=['Pays', 'Année'])

In [37]:
part['Part de la viande en protéine (%)'] = round(
    100*part['Disponibilité alimentaire (Viande) (Kcal/personne/jour)']/part['Disponibilité alimentaire (Kcal/personne/jour)'], 2)
part['Part de la viande en Kcal (%)'] = round(100*part['Disponibilité de protéines en quantité (Viande) (g/personne/jour)'] /
                                              part['Disponibilité de protéines en quantité (g/personne/jour)'], 2)

In [38]:
part = part[['Pays', 'Année',
             'Part de la viande en protéine (%)', 'Part de la viande en Kcal (%)', 'Disponibilité alimentaire (Kcal/personne/jour)']]

In [39]:
part['id'] = part['Pays'] + "/" + part['Année'].astype('str')

In [40]:
part

Élément,Pays,Année,Part de la viande en protéine (%),Part de la viande en Kcal (%),Disponibilité alimentaire (Kcal/personne/jour),id
0,Afghanistan,2017,2.43,7.21,2303.0,Afghanistan/2017
1,Afghanistan,2018,2.29,6.96,2268.0,Afghanistan/2018
2,Afghanistan,2019,2.15,6.76,2237.0,Afghanistan/2019
3,Afghanistan,2020,2.50,7.52,2239.0,Afghanistan/2020
4,Afrique du Sud,2017,11.60,33.58,2896.0,Afrique du Sud/2017
...,...,...,...,...,...,...
727,Éthiopie,2020,1.91,5.09,2406.0,Éthiopie/2020
728,Îles Salomon,2017,3.29,8.39,2404.0,Îles Salomon/2017
729,Îles Salomon,2018,3.29,8.50,2399.0,Îles Salomon/2018
730,Îles Salomon,2019,3.66,9.94,2380.0,Îles Salomon/2019
731,Îles Salomon,2020,3.27,9.68,2357.0,Îles Salomon/2020

In [41]:
part.describe()

Élément,Année,Part de la viande en protéine (%),Part de la viande en Kcal (%),Disponibilité alimentaire (Kcal/personne/jour)
count,732.000000,732.000000,732.000000,732.000000
mean,2018.516393,8.323743,21.928388,2895.935792
std,1.118678,4.718442,10.209244,454.175572
min,2017.000000,0.730000,2.510000,1740.000000
25%,2018.000000,4.567500,14.157500,2588.000000
50%,2019.000000,8.025000,22.070000,2892.500000
75%,2020.000000,11.440000,28.287500,3288.250000
max,2020.000000,27.400000,54.420000,3920.000000

Regardons maintenant l'import-export de poulets

In [42]:
im_ex = alimOri[
    (alimOri['Produit'] == "Viande de Volailles")
    &
    (alimOri['Élément'].isin(["Importations - Quantité", "Exportations - Quantité"]))]
im_ex = im_ex[['Zone', 'Élément', 'Année', 'Valeur']]
im_ex = im_ex.pivot_table(
    'Valeur', ['Zone', 'Année'], 'Élément').reset_index().fillna(0)

im_ex['import-export (milliers de tonnes)'] = im_ex['Importations - Quantité'] - \
    im_ex['Exportations - Quantité']
im_ex = im_ex[['Zone', 'Année',
               'import-export (milliers de tonnes)']].rename(columns={"Zone": "Pays"})

im_ex['id'] = im_ex['Pays'] + "/" + im_ex['Année'].astype('str')

In [43]:
im_ex

Élément,Pays,Année,import-export (milliers de tonnes),id
0,Afghanistan,2017,29.0,Afghanistan/2017
1,Afghanistan,2018,25.0,Afghanistan/2018
2,Afghanistan,2019,44.0,Afghanistan/2019
3,Afghanistan,2020,36.0,Afghanistan/2020
4,Afrique du Sud,2017,451.0,Afrique du Sud/2017
...,...,...,...,...
727,Éthiopie,2020,1.0,Éthiopie/2020
728,Îles Salomon,2017,5.0,Îles Salomon/2017
729,Îles Salomon,2018,5.0,Îles Salomon/2018
730,Îles Salomon,2019,4.0,Îles Salomon/2019
731,Îles Salomon,2020,5.0,Îles Salomon/2020

Mettons ces données avec celles sur la part de la viande

In [44]:
checkUnusedId(part, im_ex, 'id', 'id')
checkUnusedId(im_ex, part, 'id', 'id')

Auncun id non utilisé
Auncun id non utilisé

[]

In [45]:
part = pd.merge(
    part, im_ex[["id", "import-export (milliers de tonnes)"]], on="id")

In [46]:
part

Élément,Pays,Année,Part de la viande en protéine (%),Part de la viande en Kcal (%),Disponibilité alimentaire (Kcal/personne/jour),id,import-export (milliers de tonnes)
0,Afghanistan,2017,2.43,7.21,2303.0,Afghanistan/2017,29.0
1,Afghanistan,2018,2.29,6.96,2268.0,Afghanistan/2018,25.0
2,Afghanistan,2019,2.15,6.76,2237.0,Afghanistan/2019,44.0
3,Afghanistan,2020,2.50,7.52,2239.0,Afghanistan/2020,36.0
4,Afrique du Sud,2017,11.60,33.58,2896.0,Afrique du Sud/2017,451.0
...,...,...,...,...,...,...,...
727,Éthiopie,2020,1.91,5.09,2406.0,Éthiopie/2020,1.0
728,Îles Salomon,2017,3.29,8.39,2404.0,Îles Salomon/2017,5.0
729,Îles Salomon,2018,3.29,8.50,2399.0,Îles Salomon/2018,5.0
730,Îles Salomon,2019,3.66,9.94,2380.0,Îles Salomon/2019,4.0
731,Îles Salomon,2020,3.27,9.68,2357.0,Îles Salomon/2020,5.0

In [47]:
part.describe()

Élément,Année,Part de la viande en protéine (%),Part de la viande en Kcal (%),Disponibilité alimentaire (Kcal/personne/jour),import-export (milliers de tonnes)
count,732.000000,732.000000,732.000000,732.000000,732.000000
mean,2018.516393,8.323743,21.928388,2895.935792,-7.885246
std,1.118678,4.718442,10.209244,454.175572,459.563869
min,2017.000000,0.730000,2.510000,1740.000000,-4220.000000
25%,2018.000000,4.567500,14.157500,2588.000000,1.000000
50%,2019.000000,8.025000,22.070000,2892.500000,10.000000
75%,2020.000000,11.440000,28.287500,3288.250000,38.000000
max,2020.000000,27.400000,54.420000,3920.000000,1772.000000

Pour chaque pays, nous garderons : 
 <br>
 > la poulation actuelle ainsi que son évolution par rapport à l'année passée
 <br>
 la stabilité politique actuelle ainsi que son évolution par rapport à l'année passée
 <br>
 le pib actuel ainsi que son évolution par rapport à l'année passée
 <br>
 la part de la viande dans les habitudes alimentaires
 <br>
 la quantité de poulet importée-exportée (en milliers de tonnes)
 <br>
 la production de volailles (en milliers de tonnes)

Commençons par la population

In [48]:
popPrec = pop[pop['Année'] == (annee-1)]
popActu = pop[pop['Année'] == annee]
checkUnusedId(popPrec, popActu, 'Pays', 'Pays')
checkUnusedId(popActu, popPrec, 'Pays', 'Pays')
print("Tous les pays sont bien restés")

popPrec['Population '+str(annee-1)] = popPrec.loc[:, 'Population']
popActu['Population '+str(annee)] = popActu.loc[:, 'Population']
popEvo = pd.merge(popPrec[['Pays', 'Population '+str(annee-1)]],
                  popActu[['Pays', 'Population '+str(annee)]], on='Pays')
popEvo['Population évolution (%)'] = 100*(popEvo['Population '+str(
    annee)]-popEvo['Population '+str(annee-1)])/popEvo['Population '+str(annee-1)]

Auncun Pays non utilisé
Auncun Pays non utilisé
Tous les pays sont bien restés

C:\Users\thebe\AppData\Local\Temp\ipykernel_8636\572468334.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  popPrec['Population '+str(annee-1)] = popPrec.loc[:, 'Population']
C:\Users\thebe\AppData\Local\Temp\ipykernel_8636\572468334.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  popActu['Population '+str(annee)] = popActu.loc[:, 'Population']

In [49]:
popEvo

,Pays,Population 2019,Population 2020,Population évolution (%)
0,Afghanistan,38041750.0,38928350.0,2.330597
1,Afrique du Sud,58558270.0,59308690.0,1.281493
2,Albanie,2880920.0,2877800.0,-0.108299
3,Algérie,43053050.0,43851040.0,1.853504
4,Allemagne,83517040.0,83783940.0,0.319576
...,...,...,...,...
181,Venezuela (République bolivarienne du),28515830.0,28435940.0,-0.280160
182,Viet Nam,96462110.0,97338580.0,0.908616
183,Yémen,29161920.0,29825960.0,2.277079
184,Zambie,17861030.0,18383960.0,2.927771
185,Zimbabwe,14645470.0,14862920.0,1.484759

Au tour de la stabilité politique

In [50]:
stabPrec = stabilite[stabilite['Année'] == (annee-1)]
stabActu = stabilite[stabilite['Année'] == annee]
checkUnusedId(stabPrec, stabActu, 'Pays', 'Pays')
checkUnusedId(stabActu, stabPrec, 'Pays', 'Pays')
print("Tous les pays sont bien restés")

stabPrec['Stabilité Politique ' +
         str(annee-1)] = stabPrec.loc[:, 'Stabilité Politique']
stabActu['Stabilité Politique ' +
         str(annee)] = stabActu.loc[:, 'Stabilité Politique']
stabEvo = pd.merge(stabPrec[['Pays', 'Stabilité Politique '+str(annee-1)]],
                   stabActu[['Pays', 'Stabilité Politique '+str(annee)]], on='Pays')
stabEvo['Stabilité Politique évolution (%)'] = 100*(stabEvo['Stabilité Politique '+str(
    annee)]-stabEvo['Stabilité Politique '+str(annee-1)])/stabEvo['Stabilité Politique '+str(annee-1)]

Auncun Pays non utilisé
Auncun Pays non utilisé
Tous les pays sont bien restés

C:\Users\thebe\AppData\Local\Temp\ipykernel_8636\1277954364.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stabPrec['Stabilité Politique ' +
C:\Users\thebe\AppData\Local\Temp\ipykernel_8636\1277954364.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stabActu['Stabilité Politique ' +

In [51]:
stabEvo

,Pays,Stabilité Politique 2019,Stabilité Politique 2020,Stabilité Politique évolution (%)
0,Afghanistan,-2.66,-2.73,2.631579
1,Afrique du Sud,-0.27,-0.24,-11.111111
2,Albanie,0.11,0.08,-27.272727
3,Algérie,-1.04,-0.86,-17.307692
4,Allemagne,0.57,0.67,17.543860
...,...,...,...,...
194,Venezuela (République bolivarienne du),-1.54,-1.52,-1.298701
195,Viet Nam,0.03,-0.07,-333.333333
196,Yémen,-2.77,-2.67,-3.610108
197,Zambie,-0.11,-0.13,18.181818
198,Zimbabwe,-0.96,-1.08,12.500000

In [52]:
stabEvo.describe()

,Stabilité Politique 2019,Stabilité Politique 2020,Stabilité Politique évolution (%)
count,199.000000,199.000000,199.000000
mean,-0.061307,-0.058945,inf
std,0.992725,0.994801,NaN
min,-2.770000,-2.730000,-333.333333
25%,-0.660000,-0.645000,-8.792271
50%,0.010000,0.020000,0.900901
75%,0.770000,0.780000,13.288656
max,1.880000,1.910000,inf

In [53]:
stabEvo.replace([np.inf, -np.inf], 0, inplace=True)

Passons au PIB

In [54]:
pibPrec = pib[pib['Année'] == (annee-1)]
pibActu = pib[pib['Année'] == annee]
LPaysManquantActu = checkUnusedId(pibPrec, pibActu, 'Pays', 'Pays')
LPaysManquantPrec = checkUnusedId(pibActu, pibPrec, 'Pays', 'Pays')
if len(LPaysManquantActu) != 0:
    print("Il nous manque le PIB du Turkménistan en", annee,
          ", on va donc reprendre celui de l'année précédente")
    for i in LPaysManquantActu:
        pibActu = pd.concat([pibActu, pibPrec.loc[pibPrec['Pays'] == i, :]])
if len(LPaysManquantPrec) != 0:
    print("Il nous manque certains PIB en", annee-1,
          ", on va donc prendre celui de l'année suivante")
    for i in LPaysManquantActu:
        pibPrec = pd.concat([pibPrec, pibActu.loc[pibActu['Pays'] == i, :]])

checkUnusedId(pibPrec, pibActu, 'Pays', 'Pays')

pibPrec['Pib/Habitant ($/habitant) '+str(annee-1)
        ] = pibPrec.loc[:, 'Pib/Habitant ($/habitant)']
pibActu['Pib/Habitant ($/habitant) '+str(annee)
        ] = pibActu.loc[:, 'Pib/Habitant ($/habitant)']
pibEvo = pd.merge(pibPrec[['Pays', 'Pib/Habitant ($/habitant) '+str(annee-1)]],
                  pibActu[['Pays', 'Pib/Habitant ($/habitant) '+str(annee)]], on='Pays')
pibEvo['PIB évolution (%)'] = 100*(pibEvo['Pib/Habitant ($/habitant) '+str(annee)] -
                                   pibEvo['Pib/Habitant ($/habitant) '+str(annee-1)])/pibEvo['Pib/Habitant ($/habitant) '+str(annee-1)]

1 Pays non utilisé(s) ( 1 ) : ['Turkménistan']
Auncun Pays non utilisé
Il nous manque le PIB du Turkménistan en 2020 , on va donc reprendre celui de l'année précédente
Auncun Pays non utilisé

C:\Users\thebe\AppData\Local\Temp\ipykernel_8636\3534420031.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pibPrec['Pib/Habitant ($/habitant) '+str(annee-1)

In [55]:
pibEvo

,Pays,Pib/Habitant ($/habitant) 2019,Pib/Habitant ($/habitant) 2020,PIB évolution (%)
0,Afghanistan,2065.0,1970.6,-4.571429
1,Afrique du Sud,13710.0,12665.8,-7.616338
2,Albanie,13653.2,13253.7,-2.926054
3,Algérie,11522.0,10735.4,-6.826940
4,Allemagne,53929.6,51423.2,-4.647540
...,...,...,...,...
227,Pays à faible revenu et à déficit vivrier,5371.5,5081.4,-5.400726
228,Pays à faible revenu,1945.1,1908.2,-1.897075
229,Pays à revenu moyen,7318.5,6982.4,-4.592471
230,High-income economies,50435.3,47815.6,-5.194179
231,Upper-middle-income economies,19224.5,18165.8,-5.507035

In [56]:
part = part[part['Année'] == annee]

# Fusion des Tables

Nous allons tout fusionner sur la table "part" (celle contenant les informations sur la part de la viande dans la consommation alimentaire).
Vérifions donc si des pays apparaissent dans cette table mais pas dans d'autres.

In [57]:
popEvo

,Pays,Population 2019,Population 2020,Population évolution (%)
0,Afghanistan,38041750.0,38928350.0,2.330597
1,Afrique du Sud,58558270.0,59308690.0,1.281493
2,Albanie,2880920.0,2877800.0,-0.108299
3,Algérie,43053050.0,43851040.0,1.853504
4,Allemagne,83517040.0,83783940.0,0.319576
...,...,...,...,...
181,Venezuela (République bolivarienne du),28515830.0,28435940.0,-0.280160
182,Viet Nam,96462110.0,97338580.0,0.908616
183,Yémen,29161920.0,29825960.0,2.277079
184,Zambie,17861030.0,18383960.0,2.927771
185,Zimbabwe,14645470.0,14862920.0,1.484759

In [58]:
checkUnusedId(part, popEvo, 'Pays', 'Pays')
checkUnusedId(popEvo, part, 'Pays', 'Pays')
EstPrimaire(part, "Pays")
EstPrimaire(popEvo, "Pays")

Auncun Pays non utilisé
Auncun Pays non utilisé
La clé est bien unique
La clé est bien unique

In [59]:
df = pd.merge(part, popEvo[["Pays", "Population "+str(annee),
              "Population évolution (%)"]], on="Pays", how='inner')

In [60]:
df

,Pays,Année,Part de la viande en protéine (%),Part de la viande en Kcal (%),Disponibilité alimentaire (Kcal/personne/jour),id,import-export (milliers de tonnes),Population 2020,Population évolution (%)
0,Afghanistan,2020,2.50,7.52,2239.0,Afghanistan/2020,36.0,38928350.0,2.330597
1,Afrique du Sud,2020,11.63,34.21,2855.0,Afrique du Sud/2020,376.0,59308690.0,1.281493
2,Albanie,2020,7.09,15.22,3302.0,Albanie/2020,26.0,2877800.0,-0.108299
3,Algérie,2020,2.67,8.10,3486.0,Algérie/2020,-1.0,43851040.0,1.853504
4,Allemagne,2020,9.04,24.85,3630.0,Allemagne/2020,191.0,83783940.0,0.319576
...,...,...,...,...,...,...,...,...,...
181,Émirats arabes unis,2020,6.34,21.70,3075.0,Émirats arabes unis/2020,407.0,9890400.0,1.226853
182,Équateur,2020,8.67,26.72,2490.0,Équateur/2020,0.0,17643050.0,1.550566
183,États-Unis d'Amérique,2020,14.31,37.02,3920.0,États-Unis d'Amérique/2020,-3743.0,331002650.0,0.588859
184,Éthiopie,2020,1.91,5.09,2406.0,Éthiopie/2020,1.0,114963590.0,2.573959
185,Îles Salomon,2020,3.27,9.68,2357.0,Îles Salomon/2020,5.0,686880.0,2.546953

In [61]:
df

,Pays,Année,Part de la viande en protéine (%),Part de la viande en Kcal (%),Disponibilité alimentaire (Kcal/personne/jour),id,import-export (milliers de tonnes),Population 2020,Population évolution (%)
0,Afghanistan,2020,2.50,7.52,2239.0,Afghanistan/2020,36.0,38928350.0,2.330597
1,Afrique du Sud,2020,11.63,34.21,2855.0,Afrique du Sud/2020,376.0,59308690.0,1.281493
2,Albanie,2020,7.09,15.22,3302.0,Albanie/2020,26.0,2877800.0,-0.108299
3,Algérie,2020,2.67,8.10,3486.0,Algérie/2020,-1.0,43851040.0,1.853504
4,Allemagne,2020,9.04,24.85,3630.0,Allemagne/2020,191.0,83783940.0,0.319576
...,...,...,...,...,...,...,...,...,...
181,Émirats arabes unis,2020,6.34,21.70,3075.0,Émirats arabes unis/2020,407.0,9890400.0,1.226853
182,Équateur,2020,8.67,26.72,2490.0,Équateur/2020,0.0,17643050.0,1.550566
183,États-Unis d'Amérique,2020,14.31,37.02,3920.0,États-Unis d'Amérique/2020,-3743.0,331002650.0,0.588859
184,Éthiopie,2020,1.91,5.09,2406.0,Éthiopie/2020,1.0,114963590.0,2.573959
185,Îles Salomon,2020,3.27,9.68,2357.0,Îles Salomon/2020,5.0,686880.0,2.546953

In [62]:
checkUnusedId(df, stabEvo, 'Pays', 'Pays')
checkUnusedId(stabEvo, df, 'Pays', 'Pays')
EstPrimaire(df, 'Pays')
EstPrimaire(stabEvo, 'Pays')

a = 1

4 Pays non utilisé(s) ( 4 ) : ['Chine' 'Chine, continentale' 'Nouvelle-Calédonie' 'Polynésie française']
17 Pays non utilisé(s) ( 17 ) : ['Andorre' 'Bermudes' 'Brunéi Darussalam' 'Érythrée' 'Groenland'
 'Guinée équatoriale' 'Îles Cook' 'Îles Marshall' 'Nioué' 'Palaos'
 'Palestine' 'Porto Rico' 'Samoa américaines' 'Singapour' 'Somalie'
 'Tonga' 'Tuvalu']
La clé est bien unique
La clé est bien unique

On ignore les 17 pays qui apparaissent dans la table stabilité mais qui n'apparaissent pas dans la table part car, on n'a pas les données nécessaires sur ces pays pour mener à bien l'analyse. Pour les 4 autres (ceux qui n'apparaissent pas dans la table stabilité), ils auront la stabilité politique mediane.

In [63]:
stabEvo

,Pays,Stabilité Politique 2019,Stabilité Politique 2020,Stabilité Politique évolution (%)
0,Afghanistan,-2.66,-2.73,2.631579
1,Afrique du Sud,-0.27,-0.24,-11.111111
2,Albanie,0.11,0.08,-27.272727
3,Algérie,-1.04,-0.86,-17.307692
4,Allemagne,0.57,0.67,17.543860
...,...,...,...,...
194,Venezuela (République bolivarienne du),-1.54,-1.52,-1.298701
195,Viet Nam,0.03,-0.07,-333.333333
196,Yémen,-2.77,-2.67,-3.610108
197,Zambie,-0.11,-0.13,18.181818
198,Zimbabwe,-0.96,-1.08,12.500000

In [64]:
df = pd.merge(df, stabEvo[['Pays', 'Stabilité Politique '+str(annee),
              'Stabilité Politique évolution (%)']], on='Pays', how='left')

In [65]:
medPrec = stabEvo['Stabilité Politique '+str(annee-1)].median()
medActu = stabEvo['Stabilité Politique '+str(annee)].median()
df['Stabilité Politique ' +
    str(annee)] = df['Stabilité Politique '+str(annee)].fillna(medActu)
df['Stabilité Politique évolution (%)'] = df['Stabilité Politique évolution (%)'].fillna(
    100*(medActu-medPrec)/medPrec)

In [66]:
df.describe()

,Année,Part de la viande en protéine (%),Part de la viande en Kcal (%),Disponibilité alimentaire (Kcal/personne/jour),import-export (milliers de tonnes),Population 2020,Population évolution (%),Stabilité Politique 2020,Stabilité Politique évolution (%)
count,186.0,186.000000,186.000000,186.000000,186.000000,1.860000e+02,186.000000,186.000000,186.000000
mean,2020.0,8.310484,21.964301,2912.887097,0.129032,4.957317e+07,1.191570,-0.111720,23.463066
std,0.0,4.796896,10.420491,464.282839,476.915455,1.836376e+08,1.052419,0.941188,177.104340
min,2020.0,0.730000,2.510000,1745.000000,-4042.000000,1.082000e+04,-1.353080,-2.730000,-333.333333
25%,2020.0,4.800000,14.360000,2596.000000,1.000000,2.447730e+06,0.394751,-0.647500,-9.659091
50%,2020.0,7.980000,22.210000,2917.000000,10.000000,9.775375e+06,1.075219,-0.020000,0.000000
75%,2020.0,11.197500,28.180000,3313.250000,39.500000,3.120982e+07,1.930716,0.670000,16.211878
max,2020.0,27.400000,54.420000,3920.000000,1772.000000,1.471287e+09,3.843382,1.490000,1600.000000

In [67]:
df

,Pays,Année,Part de la viande en protéine (%),Part de la viande en Kcal (%),Disponibilité alimentaire (Kcal/personne/jour),id,import-export (milliers de tonnes),Population 2020,Population évolution (%),Stabilité Politique 2020,Stabilité Politique évolution (%)
0,Afghanistan,2020,2.50,7.52,2239.0,Afghanistan/2020,36.0,38928350.0,2.330597,-2.73,2.631579
1,Afrique du Sud,2020,11.63,34.21,2855.0,Afrique du Sud/2020,376.0,59308690.0,1.281493,-0.24,-11.111111
2,Albanie,2020,7.09,15.22,3302.0,Albanie/2020,26.0,2877800.0,-0.108299,0.08,-27.272727
3,Algérie,2020,2.67,8.10,3486.0,Algérie/2020,-1.0,43851040.0,1.853504,-0.86,-17.307692
4,Allemagne,2020,9.04,24.85,3630.0,Allemagne/2020,191.0,83783940.0,0.319576,0.67,17.543860
...,...,...,...,...,...,...,...,...,...,...,...
181,Émirats arabes unis,2020,6.34,21.70,3075.0,Émirats arabes unis/2020,407.0,9890400.0,1.226853,0.63,-8.695652
182,Équateur,2020,8.67,26.72,2490.0,Équateur/2020,0.0,17643050.0,1.550566,-0.36,56.521739
183,États-Unis d'Amérique,2020,14.31,37.02,3920.0,États-Unis d'Amérique/2020,-3743.0,331002650.0,0.588859,-0.02,-115.384615
184,Éthiopie,2020,1.91,5.09,2406.0,Éthiopie/2020,1.0,114963590.0,2.573959,-1.74,32.824427
185,Îles Salomon,2020,3.27,9.68,2357.0,Îles Salomon/2020,5.0,686880.0,2.546953,0.64,25.490196

In [68]:
pibEvo

,Pays,Pib/Habitant ($/habitant) 2019,Pib/Habitant ($/habitant) 2020,PIB évolution (%)
0,Afghanistan,2065.0,1970.6,-4.571429
1,Afrique du Sud,13710.0,12665.8,-7.616338
2,Albanie,13653.2,13253.7,-2.926054
3,Algérie,11522.0,10735.4,-6.826940
4,Allemagne,53929.6,51423.2,-4.647540
...,...,...,...,...
227,Pays à faible revenu et à déficit vivrier,5371.5,5081.4,-5.400726
228,Pays à faible revenu,1945.1,1908.2,-1.897075
229,Pays à revenu moyen,7318.5,6982.4,-4.592471
230,High-income economies,50435.3,47815.6,-5.194179
231,Upper-middle-income economies,19224.5,18165.8,-5.507035

In [69]:
checkUnusedId(df, pibEvo, 'Pays', 'Pays')
checkUnusedId(pibEvo, df, 'Pays', 'Pays')
a = 1

10 Pays non utilisé(s) ( 10 ) : ['Chine, Taiwan Province de' 'Chine, continentale' 'Cuba'
 'Nouvelle-Calédonie' 'Polynésie française' 'République arabe syrienne'
 'République populaire démocratique de Corée' 'Soudan du Sud'
 'Venezuela (République bolivarienne du)' 'Yémen']
56 Pays non utilisé(s) ( 56 ) : ['Bermudes' 'Brunéi Darussalam' 'Guinée équatoriale' 'Îles Marshall'
 'Palaos' 'Palestine' 'Porto Rico' 'Singapour' 'Somalie' 'Tonga' 'Tuvalu'
 'Monde' 'Afrique' 'Afrique orientale' 'Afrique centrale'
 'Afrique septentrionale' 'Afrique du Nord (Soudan Excl)'
 'Afrique australe' 'Afrique occidentale' 'Afrique subsaharienne'
 'Afrique subsaharienne (y compris Soudan)' 'Amérique du Nord et Europe'
 'Amérique septentrionale' 'Europe' 'Europe orientale'
 'Europe septentrionale' 'Europe méridionale' 'Europe occidentale'
 'Amérique latine et Caraïbes' 'Amérique centrale' 'Caraïbes'
 'Amérique du Sud' 'Asie' 'Asie centrale' 'Asie orientale'
 'Asie méridionale' 'Asie du Sud (Inde Excl)' 'Asie du Sud-Est'
 'Asie occidentale' 'Asie centrale et Asie du Sud'
 'Asie orientale et Asie du Sud-Est' 'Asie occidentale et Afrique du Nord'
 'Océanie' 'Australie et Nouvelle-Zélande' 'Mélanésie' 'Micronésie'
 'Polynésie' 'Océanie, hors Australie et Nouvelle-Zélande'
 'Pays les moins développés' 'Pays sans littoral en voie de développement'
 'Petites îles en voie de Développement'
 'Pays à faible revenu et à déficit vivrier' 'Pays à faible revenu'
 'Pays à revenu moyen' 'High-income economies'
 'Upper-middle-income economies']

Encore une fois, on ignore les 66 pays qui n'apparaissent pas dans une table ou dans l'autre. Sauf la chine auquelle on rajoute manuellement son PIB

In [70]:
pibChine = pd.read_csv(
    'data\OCDE_PIB_Chine_2018_2020.csv').query('LOCATION=="CHN"')
pibChine

,LOCATION,INDICATOR,SUBJECT,MEASURE,FREQUENCY,TIME,Value,Flag Codes
124,CHN,GDP,TOT,USD_CAP,A,2018,15466.329982,NaN
125,CHN,GDP,TOT,USD_CAP,A,2019,16624.520609,NaN
126,CHN,GDP,TOT,USD_CAP,A,2020,17176.865661,NaN
127,CHN,GDP,TOT,USD_CAP,A,2021,19334.953602,NaN

In [71]:
PIB_CHN_prec = pibChine.query('TIME==(@annee-1)')['Value'].iloc[0]
PIB_CHN_actu = pibChine.query('TIME==(@annee)')['Value'].iloc[0]
ligne = ['Chine, continentale', PIB_CHN_prec, PIB_CHN_actu,
         100*(PIB_CHN_actu-PIB_CHN_prec)/PIB_CHN_prec]
colonne = ['Pays', 'Pib/Habitant ($/habitant) '+str(annee-1),
           'Pib/Habitant ($/habitant) '+str(annee), 'PIB évolution (%)']
ligne = pd.DataFrame([ligne], columns=colonne)
pibEvo = pd.concat([pibEvo, ligne], ignore_index=True)

In [72]:
checkUnusedId(df, pibEvo, 'Pays', 'Pays')
df = pd.merge(df, pibEvo[['Pays', 'Pib/Habitant ($/habitant) ' +
              str(annee), 'PIB évolution (%)']], on='Pays', how='inner')

9 Pays non utilisé(s) ( 9 ) : ['Chine, Taiwan Province de' 'Cuba' 'Nouvelle-Calédonie'
 'Polynésie française' 'République arabe syrienne'
 'République populaire démocratique de Corée' 'Soudan du Sud'
 'Venezuela (République bolivarienne du)' 'Yémen']

In [73]:
df

,Pays,Année,Part de la viande en protéine (%),Part de la viande en Kcal (%),Disponibilité alimentaire (Kcal/personne/jour),id,import-export (milliers de tonnes),Population 2020,Population évolution (%),Stabilité Politique 2020,Stabilité Politique évolution (%),Pib/Habitant ($/habitant) 2020,PIB évolution (%)
0,Afghanistan,2020,2.50,7.52,2239.0,Afghanistan/2020,36.0,38928350.0,2.330597,-2.73,2.631579,1970.6,-4.571429
1,Afrique du Sud,2020,11.63,34.21,2855.0,Afrique du Sud/2020,376.0,59308690.0,1.281493,-0.24,-11.111111,12665.8,-7.616338
2,Albanie,2020,7.09,15.22,3302.0,Albanie/2020,26.0,2877800.0,-0.108299,0.08,-27.272727,13253.7,-2.926054
3,Algérie,2020,2.67,8.10,3486.0,Algérie/2020,-1.0,43851040.0,1.853504,-0.86,-17.307692,10735.4,-6.826940
4,Allemagne,2020,9.04,24.85,3630.0,Allemagne/2020,191.0,83783940.0,0.319576,0.67,17.543860,51423.2,-4.647540
...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,Émirats arabes unis,2020,6.34,21.70,3075.0,Émirats arabes unis/2020,407.0,9890400.0,1.226853,0.63,-8.695652,63299.4,-7.272240
173,Équateur,2020,8.67,26.72,2490.0,Équateur/2020,0.0,17643050.0,1.550566,-0.36,56.521739,10325.0,-9.195645
174,États-Unis d'Amérique,2020,14.31,37.02,3920.0,États-Unis d'Amérique/2020,-3743.0,331002650.0,0.588859,-0.02,-115.384615,59755.2,-4.328613
175,Éthiopie,2020,1.91,5.09,2406.0,Éthiopie/2020,1.0,114963590.0,2.573959,-1.74,32.824427,2296.9,3.398758
176,Îles Salomon,2020,3.27,9.68,2357.0,Îles Salomon/2020,5.0,686880.0,2.546953,0.64,25.490196,2482.4,-6.694230

Ajoutons la production de volailles

In [74]:
prodVolail = prodVolail.loc[prodVolail['Année'] == annee, :]
prodVolail

Produit,Pays,Année,Tonnes de viande de poulet produite,Milliers de poulets,id
2,Afghanistan,2020,27753.95,13697.0,Afghanistan/2020
5,Afrique du Sud,2020,1880000.00,170487.0,Afrique du Sud/2020
8,Albanie,2020,12233.91,6774.0,Albanie/2020
11,Algérie,2020,257787.09,136415.0,Algérie/2020
14,Allemagne,2020,1066000.00,19351.0,Allemagne/2020
...,...,...,...,...,...
574,Érythrée,2020,1128.61,1185.0,Érythrée/2020
577,États-Unis d'Amérique,2020,20514868.64,1537000.0,États-Unis d'Amérique/2020
580,Éthiopie,2020,67650.74,56993.0,Éthiopie/2020
583,Îles Cook,2020,15.88,17.0,Îles Cook/2020
586,Îles Salomon,2020,283.68,245.0,Îles Salomon/2020

In [75]:
checkUnusedId(df, prodVolail, 'Pays', 'Pays')

4 Pays non utilisé(s) ( 4 ) : ['Djibouti' 'Maldives' 'Roumanie' 'Slovaquie']

['Djibouti', 'Maldives', 'Roumanie', 'Slovaquie']

On ignore le pays auquelle on a pas accès à la production

In [76]:
df = pd.merge(df, prodVolail[['Pays', 'Tonnes de viande de poulet produite',
              'Milliers de poulets']], on='Pays', how='inner')

Colonne Suplémentaire

Ajoutons le PIB du Pays

In [77]:
df['PIB'] = df['Population '+str(annee)] * \
    df['Pib/Habitant ($/habitant) '+str(annee)]

In [78]:
df

,Pays,Année,Part de la viande en protéine (%),Part de la viande en Kcal (%),Disponibilité alimentaire (Kcal/personne/jour),id,import-export (milliers de tonnes),Population 2020,Population évolution (%),Stabilité Politique 2020,Stabilité Politique évolution (%),Pib/Habitant ($/habitant) 2020,PIB évolution (%),Tonnes de viande de poulet produite,Milliers de poulets,PIB
0,Afghanistan,2020,2.50,7.52,2239.0,Afghanistan/2020,36.0,38928350.0,2.330597,-2.73,2.631579,1970.6,-4.571429,27753.95,13697.0,7.671221e+10
1,Afrique du Sud,2020,11.63,34.21,2855.0,Afrique du Sud/2020,376.0,59308690.0,1.281493,-0.24,-11.111111,12665.8,-7.616338,1880000.00,170487.0,7.511920e+11
2,Albanie,2020,7.09,15.22,3302.0,Albanie/2020,26.0,2877800.0,-0.108299,0.08,-27.272727,13253.7,-2.926054,12233.91,6774.0,3.814150e+10
3,Algérie,2020,2.67,8.10,3486.0,Algérie/2020,-1.0,43851040.0,1.853504,-0.86,-17.307692,10735.4,-6.826940,257787.09,136415.0,4.707585e+11
4,Allemagne,2020,9.04,24.85,3630.0,Allemagne/2020,191.0,83783940.0,0.319576,0.67,17.543860,51423.2,-4.647540,1066000.00,19351.0,4.308438e+12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,Émirats arabes unis,2020,6.34,21.70,3075.0,Émirats arabes unis/2020,407.0,9890400.0,1.226853,0.63,-8.695652,63299.4,-7.272240,54101.00,25401.0,6.260564e+11
169,Équateur,2020,8.67,26.72,2490.0,Équateur/2020,0.0,17643050.0,1.550566,-0.36,56.521739,10325.0,-9.195645,452047.00,171642.0,1.821645e+11
170,États-Unis d'Amérique,2020,14.31,37.02,3920.0,États-Unis d'Amérique/2020,-3743.0,331002650.0,0.588859,-0.02,-115.384615,59755.2,-4.328613,20514868.64,1537000.0,1.977913e+13
171,Éthiopie,2020,1.91,5.09,2406.0,Éthiopie/2020,1.0,114963590.0,2.573959,-1.74,32.824427,2296.9,3.398758,67650.74,56993.0,2.640599e+11
172,Îles Salomon,2020,3.27,9.68,2357.0,Îles Salomon/2020,5.0,686880.0,2.546953,0.64,25.490196,2482.4,-6.694230,283.68,245.0,1.705111e+09

In [79]:
df.describe().round(3)

,Année,Part de la viande en protéine (%),Part de la viande en Kcal (%),Disponibilité alimentaire (Kcal/personne/jour),import-export (milliers de tonnes),Population 2020,Population évolution (%),Stabilité Politique 2020,Stabilité Politique évolution (%),Pib/Habitant ($/habitant) 2020,PIB évolution (%),Tonnes de viande de poulet produite,Milliers de poulets,PIB
count,173.0,173.000,173.000,173.000,173.000,1.730000e+02,173.000,173.000,173.000,173.000,173.000,1.730000e+02,173.000,1.730000e+02
mean,2020.0,8.353,22.044,2927.301,-5.613,5.228866e+07,1.220,-0.081,16.770,19356.700,-5.768,7.716906e+05,172756.936,8.594648e+11
std,0.0,4.819,10.429,459.546,493.029,1.901486e+08,1.053,0.906,156.841,19506.738,7.609,2.521102e+06,642106.729,3.127808e+12
min,2020.0,0.730,2.510,1745.000,-4042.000,1.082000e+04,-1.353,-2.730,-333.333,731.100,-54.642,0.000000e+00,5.000,1.470741e+08
25%,2020.0,4.830,15.140,2609.000,1.000,2.540910e+06,0.436,-0.640,-11.594,4857.400,-8.312,1.053641e+04,4674.000,2.886327e+10
50%,2020.0,8.100,22.240,2926.000,9.000,9.537650e+06,1.090,-0.020,0.962,12619.900,-4.734,7.328970e+04,20696.000,9.694126e+10
75%,2020.0,11.200,28.120,3326.000,36.000,3.297185e+07,1.947,0.710,14.286,27077.000,-2.440,3.127531e+05,82599.000,4.192131e+11
max,2020.0,27.400,54.420,3920.000,1772.000,1.471287e+09,3.843,1.490,1600.000,112557.000,42.789,2.051487e+07,5196760.000,2.472307e+13

Renommons les colonnes afin de simplifier l'analyse

In [80]:
df = df.rename(columns={"Part de la viande en protéine (%)": "part_proteine_viande",
                        "Part de la viande en Kcal (%)": "part_Kcal_viande",
                        "Disponibilité alimentaire (Kcal/personne/jour)": "dispo_alim",
                        "import-export (milliers de tonnes)": "imp_exp",
                        "Population "+str(annee): "population",
                        "Population évolution (%)": "population_evo",
                        "Stabilité Politique "+str(annee): "stab_pol",
                        "Stabilité Politique évolution (%)": "stab_pol_evo",
                        "Pib/Habitant ($/habitant) "+str(annee): "pib_hab",
                        "PIB évolution (%)": "pib_evo",
                        "PIB": "pib",
                        "Tonnes de viande de poulet produite": "poulet_pdt",
                        "Milliers de poulets": "nb_poulets"})
df

,Pays,Année,part_proteine_viande,part_Kcal_viande,dispo_alim,id,imp_exp,population,population_evo,stab_pol,stab_pol_evo,pib_hab,pib_evo,poulet_pdt,nb_poulets,pib
0,Afghanistan,2020,2.50,7.52,2239.0,Afghanistan/2020,36.0,38928350.0,2.330597,-2.73,2.631579,1970.6,-4.571429,27753.95,13697.0,7.671221e+10
1,Afrique du Sud,2020,11.63,34.21,2855.0,Afrique du Sud/2020,376.0,59308690.0,1.281493,-0.24,-11.111111,12665.8,-7.616338,1880000.00,170487.0,7.511920e+11
2,Albanie,2020,7.09,15.22,3302.0,Albanie/2020,26.0,2877800.0,-0.108299,0.08,-27.272727,13253.7,-2.926054,12233.91,6774.0,3.814150e+10
3,Algérie,2020,2.67,8.10,3486.0,Algérie/2020,-1.0,43851040.0,1.853504,-0.86,-17.307692,10735.4,-6.826940,257787.09,136415.0,4.707585e+11
4,Allemagne,2020,9.04,24.85,3630.0,Allemagne/2020,191.0,83783940.0,0.319576,0.67,17.543860,51423.2,-4.647540,1066000.00,19351.0,4.308438e+12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,Émirats arabes unis,2020,6.34,21.70,3075.0,Émirats arabes unis/2020,407.0,9890400.0,1.226853,0.63,-8.695652,63299.4,-7.272240,54101.00,25401.0,6.260564e+11
169,Équateur,2020,8.67,26.72,2490.0,Équateur/2020,0.0,17643050.0,1.550566,-0.36,56.521739,10325.0,-9.195645,452047.00,171642.0,1.821645e+11
170,États-Unis d'Amérique,2020,14.31,37.02,3920.0,États-Unis d'Amérique/2020,-3743.0,331002650.0,0.588859,-0.02,-115.384615,59755.2,-4.328613,20514868.64,1537000.0,1.977913e+13
171,Éthiopie,2020,1.91,5.09,2406.0,Éthiopie/2020,1.0,114963590.0,2.573959,-1.74,32.824427,2296.9,3.398758,67650.74,56993.0,2.640599e+11
172,Îles Salomon,2020,3.27,9.68,2357.0,Îles Salomon/2020,5.0,686880.0,2.546953,0.64,25.490196,2482.4,-6.694230,283.68,245.0,1.705111e+09

In [81]:
# On retire la Chine car il s'agit ici de la zone géographique et non du pays
df = df.query("Pays != 'Chine'")

In [82]:
df.to_parquet('data\Table_Finale.parquet', index=False)