In [219]:
import pandas as pd
import numpy as np

In [220]:
pop = pd.read_csv('data\FAOSTAT_Population_2017_2020.csv')
alim = pd.read_csv('data\FAOSTAT_DisponibiliteAlimentaire_2017-2020.csv')
stabilite = pd.read_csv('data\FAOSTAT_Stabilité_politique.csv')
pib = pd.read_csv('data\FAOSTAT_data_Pib_habitants.csv')
prodVolail = pd.read_csv('data\FAOSTAT_Production_Volailles.csv')

In [221]:
annee = 2020

# Nettoyage des Données

In [222]:
pop

,Code Domaine,Domaine,Code zone (M49),Zone,Code Élément,Élément,Code Produit (CPC),Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
0,FBS,Bilans Alimentaires (2010-),4,Afghanistan,511,Population totale,S2501,Population,2017,2017,1000 personnes,36296.00,X,Ciffre de sources internationales
1,FBS,Bilans Alimentaires (2010-),4,Afghanistan,511,Population totale,S2501,Population,2018,2018,1000 personnes,37172.00,X,Ciffre de sources internationales
2,FBS,Bilans Alimentaires (2010-),4,Afghanistan,511,Population totale,S2501,Population,2019,2019,1000 personnes,38041.75,X,Ciffre de sources internationales
3,FBS,Bilans Alimentaires (2010-),4,Afghanistan,511,Population totale,S2501,Population,2020,2020,1000 personnes,38928.35,X,Ciffre de sources internationales
4,FBS,Bilans Alimentaires (2010-),710,Afrique du Sud,511,Population totale,S2501,Population,2017,2017,1000 personnes,57010.00,X,Ciffre de sources internationales
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
727,FBS,Bilans Alimentaires (2010-),894,Zambie,511,Population totale,S2501,Population,2020,2020,1000 personnes,18383.96,X,Ciffre de sources internationales
728,FBS,Bilans Alimentaires (2010-),716,Zimbabwe,511,Population totale,S2501,Population,2017,2017,1000 personnes,14236.59,X,Ciffre de sources internationales
729,FBS,Bilans Alimentaires (2010-),716,Zimbabwe,511,Population totale,S2501,Population,2018,2018,1000 personnes,14438.80,X,Ciffre de sources internationales
730,FBS,Bilans Alimentaires (2010-),716,Zimbabwe,511,Population totale,S2501,Population,2019,2019,1000 personnes,14645.47,X,Ciffre de sources internationales
731,FBS,Bilans Alimentaires (2010-),716,Zimbabwe,511,Population totale,S2501,Population,2020,2020,1000 personnes,14862.92,X,Ciffre de sources internationales

In [223]:
pop.describe(include='all')

,Code Domaine,Domaine,Code zone (M49),Zone,Code Élément,Élément,Code Produit (CPC),Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
count,732,732,732.000000,732,732.0,732,732,732,732.000000,732.000000,732,7.320000e+02,732,732
unique,1,1,NaN,186,NaN,1,1,1,NaN,NaN,1,NaN,1,1
top,FBS,Bilans Alimentaires (2010-),NaN,Afghanistan,NaN,Population totale,S2501,Population,NaN,NaN,1000 personnes,NaN,X,Ciffre de sources internationales
freq,732,732,NaN,4,NaN,732,732,732,NaN,NaN,732,NaN,732,732
mean,NaN,NaN,425.740437,NaN,511.0,NaN,NaN,NaN,2018.516393,2018.516393,NaN,4.963196e+04,NaN,NaN
std,NaN,NaN,251.145689,NaN,0.0,NaN,NaN,NaN,1.118678,1.118678,NaN,1.829714e+05,NaN,NaN
min,NaN,NaN,4.000000,NaN,511.0,NaN,NaN,NaN,2017.000000,2017.000000,NaN,1.076000e+01,NaN,NaN
25%,NaN,NaN,204.000000,NaN,511.0,NaN,NaN,NaN,2018.000000,2018.000000,NaN,2.529315e+03,NaN,NaN
50%,NaN,NaN,418.000000,NaN,511.0,NaN,NaN,NaN,2019.000000,2019.000000,NaN,9.738060e+03,NaN,NaN
75%,NaN,NaN,642.000000,NaN,511.0,NaN,NaN,NaN,2020.000000,2020.000000,NaN,3.108095e+04,NaN,NaN
max,NaN,NaN,894.000000,NaN,511.0,NaN,NaN,NaN,2020.000000,2020.000000,NaN,1.471287e+06,NaN,NaN

On commence par enlever les colonnes qui ne nous servent pas, à savoir tout sauf l'année, le pays et le nombre d'habitants qu'on prend soin de multiplier par 1000 afin d'obtenir le nombre exact d'habitants.

In [224]:
pop = pop[['Zone', 'Année', 'Valeur']]
pop['Valeur'] = pop['Valeur']*1000
pop = pop.rename(columns={'Zone': 'Pays',
                          'Valeur': 'Population'})

C:\Users\thebe\AppData\Local\Temp\ipykernel_7824\1716358708.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pop['Valeur'] = pop['Valeur']*1000

On ajoute une colonne qui servira de clé primaire

In [225]:
pop['id'] = pop['Pays'] + "/" + pop['Année'].astype('str')

In [226]:
pop

               Pays  Année  Population                   id
0       Afghanistan   2017  36296000.0     Afghanistan/2017
1       Afghanistan   2018  37172000.0     Afghanistan/2018
2       Afghanistan   2019  38041750.0     Afghanistan/2019
3       Afghanistan   2020  38928350.0     Afghanistan/2020
4    Afrique du Sud   2017  57010000.0  Afrique du Sud/2017
..              ...    ...         ...                  ...
727          Zambie   2020  18383960.0          Zambie/2020
728        Zimbabwe   2017  14236590.0        Zimbabwe/2017
729        Zimbabwe   2018  14438800.0        Zimbabwe/2018
730        Zimbabwe   2019  14645470.0        Zimbabwe/2019
731        Zimbabwe   2020  14862920.0        Zimbabwe/2020

[732 rows x 4 columns]

On vérifie que la clé est bien unique

In [227]:
def EstPrimaire(df, id):
    if df[id].nunique() == len(df):
        print("La clé est bien unique")
    else:
        print("la clé n'est pas unique")


EstPrimaire(pop, 'id')

La clé est bien unique

On s'occupe de la table "stabilite" qui concerne la stabilité politique du pays

In [228]:
stabilite

,Code Domaine,Domaine,Code zone (M49),Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,FS,Données de la sécurité alimentaire,4,Afghanistan,6125,Valeur,21032,Stabilité politique et absence de violence/ter...,2000,2000,indice,-2.44,X,Ciffre de sources internationales,NaN
1,FS,Données de la sécurité alimentaire,4,Afghanistan,6125,Valeur,21032,Stabilité politique et absence de violence/ter...,2002,2002,indice,-2.04,X,Ciffre de sources internationales,NaN
2,FS,Données de la sécurité alimentaire,4,Afghanistan,6125,Valeur,21032,Stabilité politique et absence de violence/ter...,2003,2003,indice,-2.20,X,Ciffre de sources internationales,NaN
3,FS,Données de la sécurité alimentaire,4,Afghanistan,6125,Valeur,21032,Stabilité politique et absence de violence/ter...,2004,2004,indice,-2.30,X,Ciffre de sources internationales,NaN
4,FS,Données de la sécurité alimentaire,4,Afghanistan,6125,Valeur,21032,Stabilité politique et absence de violence/ter...,2005,2005,indice,-2.07,X,Ciffre de sources internationales,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3903,FS,Données de la sécurité alimentaire,716,Zimbabwe,6125,Valeur,21032,Stabilité politique et absence de violence/ter...,2016,2016,indice,-0.62,X,Ciffre de sources internationales,NaN
3904,FS,Données de la sécurité alimentaire,716,Zimbabwe,6125,Valeur,21032,Stabilité politique et absence de violence/ter...,2017,2017,indice,-0.71,X,Ciffre de sources internationales,NaN
3905,FS,Données de la sécurité alimentaire,716,Zimbabwe,6125,Valeur,21032,Stabilité politique et absence de violence/ter...,2018,2018,indice,-0.72,X,Ciffre de sources internationales,NaN
3906,FS,Données de la sécurité alimentaire,716,Zimbabwe,6125,Valeur,21032,Stabilité politique et absence de violence/ter...,2019,2019,indice,-0.96,X,Ciffre de sources internationales,NaN
3907,FS,Données de la sécurité alimentaire,716,Zimbabwe,6125,Valeur,21032,Stabilité politique et absence de violence/ter...,2020,2020,indice,-1.08,X,Ciffre de sources internationales,NaN

On ignore ce qui ne nous sert pas

In [229]:
stabilite = stabilite[['Zone', 'Année', 'Valeur']]

On crée une clé primaire comme précédemment

In [230]:
stabilite['id'] = stabilite['Zone']+"/" + stabilite['Année'].astype('str')
stabilite = stabilite.rename(columns={'Zone': 'Pays',
                                      'Valeur': 'Stabilité Politique'})
EstPrimaire(stabilite, 'id')

La clé est bien unique

C:\Users\thebe\AppData\Local\Temp\ipykernel_7824\3708130892.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stabilite['id'] = stabilite['Zone']+"/" + stabilite['Année'].astype('str')

In [231]:
stabilite.describe()

             Année  Stabilité Politique
count  3908.000000          3908.000000
mean   2010.542733            -0.050000
std       5.827217             0.997415
min    2000.000000            -3.310000
25%    2006.000000            -0.710000
50%    2011.000000             0.055000
75%    2016.000000             0.800000
max    2020.000000             1.970000

On s'occupe de la table pib qui contient le pib par habitant

In [232]:
pib.describe(include='all')

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
count,2533,2533,2533.000000,2533,2533.0,2533,2533.0,2533,2533.000000,2533.000000,2533,2533.000000,2533,2533,0.0
unique,1,1,NaN,232,NaN,1,NaN,1,NaN,NaN,1,NaN,1,1,NaN
top,FS,Données de la sécurité alimentaire,NaN,Myanmar,NaN,Valeur,NaN,"PIB par habitant, ($ PPA internationaux consta...",NaN,NaN,I$,NaN,X,Ciffre de sources internationales,NaN
freq,2533,2533,NaN,11,NaN,2533,NaN,2533,NaN,NaN,2533,NaN,2533,2533,NaN
mean,NaN,NaN,1147.318595,NaN,6126.0,NaN,22013.0,NaN,2015.003948,2015.003948,NaN,19464.324872,NaN,NaN,NaN
std,NaN,NaN,2149.175706,NaN,0.0,NaN,0.0,NaN,5.442358,5.442358,NaN,20625.032001,NaN,NaN,NaN
min,NaN,NaN,1.000000,NaN,6126.0,NaN,22013.0,NaN,2000.000000,2000.000000,NaN,630.700000,NaN,NaN,NaN
25%,NaN,NaN,84.000000,NaN,6126.0,NaN,22013.0,NaN,2013.000000,2013.000000,NaN,4527.700000,NaN,NaN,NaN
50%,NaN,NaN,156.000000,NaN,6126.0,NaN,22013.0,NaN,2016.000000,2016.000000,NaN,12357.900000,NaN,NaN,NaN
75%,NaN,NaN,235.000000,NaN,6126.0,NaN,22013.0,NaN,2019.000000,2019.000000,NaN,27797.100000,NaN,NaN,NaN
max,NaN,NaN,9011.000000,NaN,6126.0,NaN,22013.0,NaN,2021.000000,2021.000000,NaN,161972.000000,NaN,NaN,NaN

In [233]:
pib = pib[['Zone', 'Année', 'Valeur']]
pib = pib.rename(columns={'Zone': 'Pays',
                          'Valeur': 'Pib/Habitant ($/habitant)'})

In [234]:
pib['id'] = pib['Pays'] + "/" + pib['Année'].astype('str')
EstPrimaire(pib, 'id')

La clé est bien unique

In [235]:
def checkUnusedId(dfToRmv, df2, id1, id2):
    listToRmv = dfToRmv[id1].tolist()
    listDf2 = df2[id2].tolist()
    tempo = []

    for i in listToRmv:
        if i in listDf2:
            tempo.append(i)
    for i in tempo:
        listToRmv.remove(i)

    if len(listToRmv) != 0:
        listToRmvUnique = pd.Series(listToRmv).unique()
        print(len(listToRmvUnique), id1, "non utilisé(s) (",
              len(listToRmv), ") :", listToRmvUnique)
    else:
        print("Auncun", id1, "non utilisé")
    # dfToRmv = dfToRmv.drop(dfToRmv[dfToRmv[id1].isin(listToRmv)].index)

    return listToRmv

In [236]:
# checkUnusedId(pop[pop['Année']==2017], pib[pib['Année']==2017], 'id', 'id')
# checkUnusedId(pop[pop['Année']==2017], stabilite[stabilite['Année']==2017], 'id', 'id')
# checkUnusedId(pib[pib['Année']==2017], pop[pop['Année']==2017], 'id', 'id')
# checkUnusedId(pib[pib['Année']==2017], stabilite[stabilite['Année']==2017], 'id', 'id')
# checkUnusedId(stabilite[stabilite['Année']==2017], pop[pop['Année']==2017], 'id', 'id')
# checkUnusedId(stabilite[stabilite['Année']==2017], pib[pib['Année']==2017], 'id', 'id')

On s'occupe de la table ProdVollail

In [237]:
prodVolail = prodVolail[['Zone', 'Année', 'Valeur']].rename(columns={'Zone':'Pays', 'Valeur':'Production de Volailles'})
prodVolail = prodVolail.loc[prodVolail['Année']==annee,:]

In [238]:
prodVolail

                                        Pays  Année  Production de Volailles
10                               Afghanistan   2020                       28
21                            Afrique du Sud   2020                     1881
32                                   Albanie   2020                       14
43                                   Algérie   2020                      284
54                                 Allemagne   2020                     1572
...                                      ...    ...                      ...
1919  Venezuela (République bolivarienne du)   2020                      457
1930                                Viet Nam   2020                     1319
1941                                   Yémen   2020                      195
1952                                  Zambie   2020                       52
1963                                Zimbabwe   2020                       67

[184 rows x 3 columns]

In [239]:
prodVolail.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 184 entries, 10 to 1963
Data columns (total 3 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Pays                     184 non-null    object
 1   Année                    184 non-null    int64
 2   Production de Volailles  184 non-null    int64
dtypes: int64(2), object(1)
memory usage: 5.8+ KB

On s'occupe maintenant de la table "alim"

In [240]:
alim['Année'].unique()

array([2017, 2018, 2019, 2020], dtype=int64)

On crée une copie pour pouvoir revenir à ces données plus tard

In [241]:
alimOri = alim.copy()

In [242]:
alim

,Domaine,Zone,Élément,Produit,Année,Unité,Valeur
0,Bilans Alimentaires (2010-),Afghanistan,Importations - Quantité,Blé et produits,2017,Milliers de tonnes,3080.00
1,Bilans Alimentaires (2010-),Afghanistan,Importations - Quantité,Blé et produits,2018,Milliers de tonnes,3419.00
2,Bilans Alimentaires (2010-),Afghanistan,Importations - Quantité,Blé et produits,2019,Milliers de tonnes,2534.00
3,Bilans Alimentaires (2010-),Afghanistan,Importations - Quantité,Blé et produits,2020,Milliers de tonnes,2741.00
4,Bilans Alimentaires (2010-),Afghanistan,Exportations - Quantité,Blé et produits,2017,Milliers de tonnes,2.00
...,...,...,...,...,...,...,...
241475,Bilans Alimentaires (2010-),Zimbabwe,Disponibilité alimentaire (Kcal/personne/jour),Miscellanees,2020,Kcal/personne/jour,1.00
241476,Bilans Alimentaires (2010-),Zimbabwe,Disponibilité de protéines en quantité (g/pers...,Miscellanees,2017,g/personne/jour,0.03
241477,Bilans Alimentaires (2010-),Zimbabwe,Disponibilité de protéines en quantité (g/pers...,Miscellanees,2018,g/personne/jour,0.04
241478,Bilans Alimentaires (2010-),Zimbabwe,Disponibilité de protéines en quantité (g/pers...,Miscellanees,2019,g/personne/jour,0.09
241479,Bilans Alimentaires (2010-),Zimbabwe,Disponibilité de protéines en quantité (g/pers...,Miscellanees,2020,g/personne/jour,0.03

On ne garde que la colonne 'nourriture' qui correspond à l'utilisation liée à l'alimentation humaine

In [243]:
alim = alim[alim['Élément'].isin(['Disponibilité alimentaire (Kcal/personne/jour)',
                                 'Disponibilité de protéines en quantité (g/personne/jour)'])]

Retirons les colonnes inutiles

In [244]:
alim = alim[['Zone', 'Année', 'Élément', 'Valeur', 'Produit']]
alim = alim.rename(columns={'Zone': 'Pays'})

In [245]:
"""
L = []
for i in alim['Produit'].unique():
    if i.lower().find("viande")!=-1:
        L.append(i)
L
"""

'\nL = []\nfor i in alim[\'Produit\'].unique():\n    if i.lower().find("viande")!=-1:\n        L.append(i)\nL\n'

Créons maintenant un tableau contenant la part de la viande animale dans la consommation en Kcal et en gramme de protéines par personne

In [246]:
Viande_List = ['Viande de Bovins', "Viande d'Ovins/Caprins", 'Viande de porcins',
               'Viande de Suides', "Viande de Volailles", "Viande, Autre", "Abats Comestible"]

Calculons d'abord la consommation totale

In [247]:
part = alim.groupby(['Pays', 'Année', 'Élément'])['Valeur'].sum().reset_index(
).pivot_table('Valeur', ['Pays', 'Année'], 'Élément').reset_index()
part

Élément,Pays,Année,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité de protéines en quantité (g/personne/jour)
0,Afghanistan,2017,2303.0,59.51
1,Afghanistan,2018,2268.0,57.65
2,Afghanistan,2019,2237.0,56.06
3,Afghanistan,2020,2239.0,56.65
4,Afrique du Sud,2017,2896.0,79.68
...,...,...,...,...
727,Éthiopie,2020,2406.0,74.10
728,Îles Salomon,2017,2404.0,53.42
729,Îles Salomon,2018,2399.0,52.70
730,Îles Salomon,2019,2380.0,51.71
731,Îles Salomon,2020,2357.0,49.77

et maintenant la consommation de viande animale

In [248]:
alimViande = alim[alim['Produit'].isin(Viande_List)]
alimViande = alimViande.groupby(['Pays', 'Année', 'Élément'])['Valeur'].sum(
).reset_index().pivot_table('Valeur', ['Pays', 'Année'], 'Élément').reset_index()
alimViande = alimViande.rename(columns={'Disponibilité alimentaire (Kcal/personne/jour)': 'Disponibilité alimentaire (Viande) (Kcal/personne/jour)',
                                        'Disponibilité de protéines en quantité (g/personne/jour)': 'Disponibilité de protéines en quantité (Viande) (g/personne/jour)'})

In [249]:
part = pd.merge(part, alimViande, on=['Pays', 'Année'])

In [250]:
part['Part de la viande en protéine (%)'] = round(
    100*part['Disponibilité alimentaire (Viande) (Kcal/personne/jour)']/part['Disponibilité alimentaire (Kcal/personne/jour)'], 2)
part['Part de la viande en Kcal (%)'] = round(100*part['Disponibilité de protéines en quantité (Viande) (g/personne/jour)'] /
                                              part['Disponibilité de protéines en quantité (g/personne/jour)'], 2)

In [251]:
part = part[['Pays', 'Année',
             'Part de la viande en protéine (%)', 'Part de la viande en Kcal (%)']]

In [252]:
part['id'] = part['Pays'] + "/" + part['Année'].astype('str')

In [253]:
part

Élément,Pays,Année,Part de la viande en protéine (%),Part de la viande en Kcal (%),id
0,Afghanistan,2017,2.43,7.21,Afghanistan/2017
1,Afghanistan,2018,2.29,6.96,Afghanistan/2018
2,Afghanistan,2019,2.15,6.76,Afghanistan/2019
3,Afghanistan,2020,2.50,7.52,Afghanistan/2020
4,Afrique du Sud,2017,11.60,33.58,Afrique du Sud/2017
...,...,...,...,...,...
727,Éthiopie,2020,1.91,5.09,Éthiopie/2020
728,Îles Salomon,2017,3.29,8.39,Îles Salomon/2017
729,Îles Salomon,2018,3.29,8.50,Îles Salomon/2018
730,Îles Salomon,2019,3.66,9.94,Îles Salomon/2019
731,Îles Salomon,2020,3.27,9.68,Îles Salomon/2020

In [254]:
part.describe()

Élément,Année,Part de la viande en protéine (%),Part de la viande en Kcal (%)
count,732.000000,732.000000,732.000000
mean,2018.516393,8.323743,21.928388
std,1.118678,4.718442,10.209244
min,2017.000000,0.730000,2.510000
25%,2018.000000,4.567500,14.157500
50%,2019.000000,8.025000,22.070000
75%,2020.000000,11.440000,28.287500
max,2020.000000,27.400000,54.420000

Regardons maintenant l'import-export de poulets

In [255]:
im_ex = alimOri[
    (alimOri['Produit'] == "Viande de Volailles")
    &
    (alimOri['Élément'].isin(["Importations - Quantité", "Exportations - Quantité"]))]
im_ex = im_ex[['Zone', 'Élément', 'Année', 'Valeur']]
im_ex = im_ex.pivot_table(
    'Valeur', ['Zone', 'Année'], 'Élément').reset_index().fillna(0)

im_ex['import-export (milliers de tonnes)'] = im_ex['Importations - Quantité'] - \
    im_ex['Exportations - Quantité']
im_ex = im_ex[['Zone', 'Année',
               'import-export (milliers de tonnes)']].rename(columns={"Zone": "Pays"})

im_ex['id'] = im_ex['Pays'] + "/" + im_ex['Année'].astype('str')

In [256]:
im_ex

Élément,Pays,Année,import-export (milliers de tonnes),id
0,Afghanistan,2017,29.0,Afghanistan/2017
1,Afghanistan,2018,25.0,Afghanistan/2018
2,Afghanistan,2019,44.0,Afghanistan/2019
3,Afghanistan,2020,36.0,Afghanistan/2020
4,Afrique du Sud,2017,451.0,Afrique du Sud/2017
...,...,...,...,...
727,Éthiopie,2020,1.0,Éthiopie/2020
728,Îles Salomon,2017,5.0,Îles Salomon/2017
729,Îles Salomon,2018,5.0,Îles Salomon/2018
730,Îles Salomon,2019,4.0,Îles Salomon/2019
731,Îles Salomon,2020,5.0,Îles Salomon/2020

Mettons ces données avec celles sur la part de la viande

In [257]:
checkUnusedId(part, im_ex, 'id', 'id')
checkUnusedId(im_ex, part, 'id', 'id')

Auncun id non utilisé
Auncun id non utilisé

[]

In [258]:
part = pd.merge(
    part, im_ex[["id", "import-export (milliers de tonnes)"]], on="id")

In [259]:
part

Élément,Pays,Année,Part de la viande en protéine (%),Part de la viande en Kcal (%),id,import-export (milliers de tonnes)
0,Afghanistan,2017,2.43,7.21,Afghanistan/2017,29.0
1,Afghanistan,2018,2.29,6.96,Afghanistan/2018,25.0
2,Afghanistan,2019,2.15,6.76,Afghanistan/2019,44.0
3,Afghanistan,2020,2.50,7.52,Afghanistan/2020,36.0
4,Afrique du Sud,2017,11.60,33.58,Afrique du Sud/2017,451.0
...,...,...,...,...,...,...
727,Éthiopie,2020,1.91,5.09,Éthiopie/2020,1.0
728,Îles Salomon,2017,3.29,8.39,Îles Salomon/2017,5.0
729,Îles Salomon,2018,3.29,8.50,Îles Salomon/2018,5.0
730,Îles Salomon,2019,3.66,9.94,Îles Salomon/2019,4.0
731,Îles Salomon,2020,3.27,9.68,Îles Salomon/2020,5.0

In [260]:
part.describe()

Élément,Année,Part de la viande en protéine (%),Part de la viande en Kcal (%),import-export (milliers de tonnes)
count,732.000000,732.000000,732.000000,732.000000
mean,2018.516393,8.323743,21.928388,-7.885246
std,1.118678,4.718442,10.209244,459.563869
min,2017.000000,0.730000,2.510000,-4220.000000
25%,2018.000000,4.567500,14.157500,1.000000
50%,2019.000000,8.025000,22.070000,10.000000
75%,2020.000000,11.440000,28.287500,38.000000
max,2020.000000,27.400000,54.420000,1772.000000

Vérifions maintenant si des pays manquent dans les données

Pour chaque pays, nous garderons : 
 <br>
 > la poulation actuelle ainsi que son évolution par rapport à l'année passée
 <br>
 la stabilité politique actuelle ainsi que son évolution par rapport à l'année passée
 <br>
 le pib actuel ainsi que son évolution par rapport à l'année passée
 <br>
 la part de la viande dans les habitudes alimentaires
 <br>
 la quantité de poulet importée-exportée (en milliers de tonnes)
 <br>
 la production de volailles (en milliers de tonnes)

Commençons par la population

In [261]:
popPrec = pop[pop['Année'] == (annee-1)]
popActu = pop[pop['Année'] == annee]
checkUnusedId(popPrec, popActu, 'Pays', 'Pays')
checkUnusedId(popActu, popPrec, 'Pays', 'Pays')
print("Tous les pays sont bien restés")

popPrec['Population '+str(annee-1)] = popPrec.loc[:, 'Population']
popActu['Population '+str(annee)] = popActu.loc[:, 'Population']
popEvo = pd.merge(popPrec[['Pays', 'Population '+str(annee-1)]],
                  popActu[['Pays', 'Population '+str(annee)]], on='Pays')
popEvo['Population évolution (%)'] = 100*(popEvo['Population '+str(
    annee)]-popEvo['Population '+str(annee-1)])/popEvo['Population '+str(annee-1)]

Auncun Pays non utilisé
Auncun Pays non utilisé
Tous les pays sont bien restés

C:\Users\thebe\AppData\Local\Temp\ipykernel_7824\572468334.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  popPrec['Population '+str(annee-1)] = popPrec.loc[:, 'Population']
C:\Users\thebe\AppData\Local\Temp\ipykernel_7824\572468334.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  popActu['Population '+str(annee)] = popActu.loc[:, 'Population']

In [262]:
popEvo

,Pays,Population 2019,Population 2020,Population évolution (%)
0,Afghanistan,38041750.0,38928350.0,2.330597
1,Afrique du Sud,58558270.0,59308690.0,1.281493
2,Albanie,2880920.0,2877800.0,-0.108299
3,Algérie,43053050.0,43851040.0,1.853504
4,Allemagne,83517040.0,83783940.0,0.319576
...,...,...,...,...
181,Venezuela (République bolivarienne du),28515830.0,28435940.0,-0.280160
182,Viet Nam,96462110.0,97338580.0,0.908616
183,Yémen,29161920.0,29825960.0,2.277079
184,Zambie,17861030.0,18383960.0,2.927771
185,Zimbabwe,14645470.0,14862920.0,1.484759

Au tour de la stabilité politique

In [263]:
stabPrec = stabilite[stabilite['Année'] == (annee-1)]
stabActu = stabilite[stabilite['Année'] == annee]
checkUnusedId(stabPrec, stabActu, 'Pays', 'Pays')
checkUnusedId(stabActu, stabPrec, 'Pays', 'Pays')
print("Tous les pays sont bien restés")

stabPrec['Stabilité Politique ' +
         str(annee-1)] = stabPrec.loc[:, 'Stabilité Politique']
stabActu['Stabilité Politique ' +
         str(annee)] = stabActu.loc[:, 'Stabilité Politique']
stabEvo = pd.merge(stabPrec[['Pays', 'Stabilité Politique '+str(annee-1)]],
                   stabActu[['Pays', 'Stabilité Politique '+str(annee)]], on='Pays')
stabEvo['Stabilité Politique évolution (%)'] = 100*(stabEvo['Stabilité Politique '+str(
    annee)]-stabEvo['Stabilité Politique '+str(annee-1)])/stabEvo['Stabilité Politique '+str(annee-1)]

Auncun Pays non utilisé
Auncun Pays non utilisé
Tous les pays sont bien restés

C:\Users\thebe\AppData\Local\Temp\ipykernel_7824\1277954364.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stabPrec['Stabilité Politique ' +
C:\Users\thebe\AppData\Local\Temp\ipykernel_7824\1277954364.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stabActu['Stabilité Politique ' +

In [264]:
stabEvo

,Pays,Stabilité Politique 2019,Stabilité Politique 2020,Stabilité Politique évolution (%)
0,Afghanistan,-2.66,-2.73,2.631579
1,Afrique du Sud,-0.27,-0.24,-11.111111
2,Albanie,0.11,0.08,-27.272727
3,Algérie,-1.04,-0.86,-17.307692
4,Allemagne,0.57,0.67,17.543860
...,...,...,...,...
194,Venezuela (République bolivarienne du),-1.54,-1.52,-1.298701
195,Viet Nam,0.03,-0.07,-333.333333
196,Yémen,-2.77,-2.67,-3.610108
197,Zambie,-0.11,-0.13,18.181818
198,Zimbabwe,-0.96,-1.08,12.500000

Passons au PIB

In [265]:
pibPrec = pib[pib['Année'] == (annee-1)]
pibActu = pib[pib['Année'] == annee]
LPaysManquantActu = checkUnusedId(pibPrec, pibActu, 'Pays', 'Pays')
LPaysManquantPrec = checkUnusedId(pibActu, pibPrec, 'Pays', 'Pays')
if len(LPaysManquantActu) != 0:
    print("Il nous manque le PIB du Turkménistan en", annee,
          ", on va donc reprendre celui de l'année précédente")
    for i in LPaysManquantActu:
        pibActu = pd.concat([pibActu, pibPrec.loc[pibPrec['Pays'] == i, :]])
if len(LPaysManquantPrec) != 0:
    print("Il nous manque certains PIB en", annee-1,
          ", on va donc prendre celui de l'année suivante")
    for i in LPaysManquantActu:
        pibPrec = pd.concat([pibPrec, pibActu.loc[pibActu['Pays'] == i, :]])

checkUnusedId(pibPrec, pibActu, 'Pays', 'Pays')

pibPrec['Pib/Habitant ($/habitant) '+str(annee-1)
        ] = pibPrec.loc[:, 'Pib/Habitant ($/habitant)']
pibActu['Pib/Habitant ($/habitant) '+str(annee)
        ] = pibActu.loc[:, 'Pib/Habitant ($/habitant)']
pibEvo = pd.merge(pibPrec[['Pays', 'Pib/Habitant ($/habitant) '+str(annee-1)]],
                  pibActu[['Pays', 'Pib/Habitant ($/habitant) '+str(annee)]], on='Pays')
pibEvo['PIB évolution (%)'] = 100*(pibEvo['Pib/Habitant ($/habitant) '+str(annee)] -
                                   pibEvo['Pib/Habitant ($/habitant) '+str(annee-1)])/pibEvo['Pib/Habitant ($/habitant) '+str(annee-1)]

1 Pays non utilisé(s) ( 1 ) : ['Turkménistan']
Auncun Pays non utilisé
Il nous manque le PIB du Turkménistan en 2020 , on va donc reprendre celui de l'année précédente
Auncun Pays non utilisé

C:\Users\thebe\AppData\Local\Temp\ipykernel_7824\3534420031.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pibPrec['Pib/Habitant ($/habitant) '+str(annee-1)

In [266]:
pibEvo

,Pays,Pib/Habitant ($/habitant) 2019,Pib/Habitant ($/habitant) 2020,PIB évolution (%)
0,Afghanistan,2065.0,1970.6,-4.571429
1,Afrique du Sud,13710.0,12665.8,-7.616338
2,Albanie,13653.2,13253.7,-2.926054
3,Algérie,11522.0,10735.4,-6.826940
4,Allemagne,53929.6,51423.2,-4.647540
...,...,...,...,...
227,Pays à faible revenu et à déficit vivrier,5371.5,5081.4,-5.400726
228,Pays à faible revenu,1945.1,1908.2,-1.897075
229,Pays à revenu moyen,7318.5,6982.4,-4.592471
230,High-income economies,50435.3,47815.6,-5.194179
231,Upper-middle-income economies,19224.5,18165.8,-5.507035

In [267]:
part = part[part['Année'] == annee]

# Fusion des Tables

Nous allons tout fusionner sur la table "part" (celle contenant les informations sur la part de la viande dans la consommation alimentaire).
Vérifions donc si des pays apparaissent dans cette table mais pas dans d'autres.

In [268]:
popEvo

,Pays,Population 2019,Population 2020,Population évolution (%)
0,Afghanistan,38041750.0,38928350.0,2.330597
1,Afrique du Sud,58558270.0,59308690.0,1.281493
2,Albanie,2880920.0,2877800.0,-0.108299
3,Algérie,43053050.0,43851040.0,1.853504
4,Allemagne,83517040.0,83783940.0,0.319576
...,...,...,...,...
181,Venezuela (République bolivarienne du),28515830.0,28435940.0,-0.280160
182,Viet Nam,96462110.0,97338580.0,0.908616
183,Yémen,29161920.0,29825960.0,2.277079
184,Zambie,17861030.0,18383960.0,2.927771
185,Zimbabwe,14645470.0,14862920.0,1.484759

In [269]:
checkUnusedId(part, popEvo, 'Pays', 'Pays')
checkUnusedId(popEvo, part, 'Pays', 'Pays')
EstPrimaire(part, "Pays")
EstPrimaire(popEvo, "Pays")

Auncun Pays non utilisé
Auncun Pays non utilisé
La clé est bien unique
La clé est bien unique

In [270]:
df = pd.merge(part, popEvo[["Pays", "Population "+str(annee),
              "Population évolution (%)"]], on="Pays", how='inner')

In [271]:
df

,Pays,Année,Part de la viande en protéine (%),Part de la viande en Kcal (%),id,import-export (milliers de tonnes),Population 2020,Population évolution (%)
0,Afghanistan,2020,2.50,7.52,Afghanistan/2020,36.0,38928350.0,2.330597
1,Afrique du Sud,2020,11.63,34.21,Afrique du Sud/2020,376.0,59308690.0,1.281493
2,Albanie,2020,7.09,15.22,Albanie/2020,26.0,2877800.0,-0.108299
3,Algérie,2020,2.67,8.10,Algérie/2020,-1.0,43851040.0,1.853504
4,Allemagne,2020,9.04,24.85,Allemagne/2020,191.0,83783940.0,0.319576
...,...,...,...,...,...,...,...,...
181,Émirats arabes unis,2020,6.34,21.70,Émirats arabes unis/2020,407.0,9890400.0,1.226853
182,Équateur,2020,8.67,26.72,Équateur/2020,0.0,17643050.0,1.550566
183,États-Unis d'Amérique,2020,14.31,37.02,États-Unis d'Amérique/2020,-3743.0,331002650.0,0.588859
184,Éthiopie,2020,1.91,5.09,Éthiopie/2020,1.0,114963590.0,2.573959
185,Îles Salomon,2020,3.27,9.68,Îles Salomon/2020,5.0,686880.0,2.546953

In [272]:
df

,Pays,Année,Part de la viande en protéine (%),Part de la viande en Kcal (%),id,import-export (milliers de tonnes),Population 2020,Population évolution (%)
0,Afghanistan,2020,2.50,7.52,Afghanistan/2020,36.0,38928350.0,2.330597
1,Afrique du Sud,2020,11.63,34.21,Afrique du Sud/2020,376.0,59308690.0,1.281493
2,Albanie,2020,7.09,15.22,Albanie/2020,26.0,2877800.0,-0.108299
3,Algérie,2020,2.67,8.10,Algérie/2020,-1.0,43851040.0,1.853504
4,Allemagne,2020,9.04,24.85,Allemagne/2020,191.0,83783940.0,0.319576
...,...,...,...,...,...,...,...,...
181,Émirats arabes unis,2020,6.34,21.70,Émirats arabes unis/2020,407.0,9890400.0,1.226853
182,Équateur,2020,8.67,26.72,Équateur/2020,0.0,17643050.0,1.550566
183,États-Unis d'Amérique,2020,14.31,37.02,États-Unis d'Amérique/2020,-3743.0,331002650.0,0.588859
184,Éthiopie,2020,1.91,5.09,Éthiopie/2020,1.0,114963590.0,2.573959
185,Îles Salomon,2020,3.27,9.68,Îles Salomon/2020,5.0,686880.0,2.546953

In [273]:
checkUnusedId(df, stabEvo, 'Pays', 'Pays')
checkUnusedId(stabEvo, df, 'Pays', 'Pays')
EstPrimaire(df, 'Pays')
EstPrimaire(stabEvo, 'Pays')

a = 1

4 Pays non utilisé(s) ( 4 ) : ['Chine' 'Chine, continentale' 'Nouvelle-Calédonie' 'Polynésie française']
17 Pays non utilisé(s) ( 17 ) : ['Andorre' 'Bermudes' 'Brunéi Darussalam' 'Érythrée' 'Groenland'
 'Guinée équatoriale' 'Îles Cook' 'Îles Marshall' 'Nioué' 'Palaos'
 'Palestine' 'Porto Rico' 'Samoa américaines' 'Singapour' 'Somalie'
 'Tonga' 'Tuvalu']
La clé est bien unique
La clé est bien unique

On ignore les 17 pays qui apparaissent dans la table stabilité mais qui n'apparaissent pas dans la table part car, on n'a pas les données nécessaires sur ces pays pour mener à bien l'analyse. Pour les 4 autres (ceux qui n'apparaissent pas dans la table stabilité), ils auront la stabilité politique mediane.

In [274]:
stabEvo

,Pays,Stabilité Politique 2019,Stabilité Politique 2020,Stabilité Politique évolution (%)
0,Afghanistan,-2.66,-2.73,2.631579
1,Afrique du Sud,-0.27,-0.24,-11.111111
2,Albanie,0.11,0.08,-27.272727
3,Algérie,-1.04,-0.86,-17.307692
4,Allemagne,0.57,0.67,17.543860
...,...,...,...,...
194,Venezuela (République bolivarienne du),-1.54,-1.52,-1.298701
195,Viet Nam,0.03,-0.07,-333.333333
196,Yémen,-2.77,-2.67,-3.610108
197,Zambie,-0.11,-0.13,18.181818
198,Zimbabwe,-0.96,-1.08,12.500000

In [275]:
df = pd.merge(df, stabEvo[['Pays', 'Stabilité Politique '+str(annee),
              'Stabilité Politique évolution (%)']], on='Pays', how='left')
medPrec = stabEvo['Stabilité Politique '+str(annee-1)].median()
medActu = stabEvo['Stabilité Politique '+str(annee)].median()
medPer = 100*(medActu-medPrec)/medPrec
Lmanquant = checkUnusedId(df, stabEvo, 'Pays', 'Pays')
df.loc[df['Pays'].isin(Lmanquant), 'Stabilité Politique '+str(annee)] = medActu
df.loc[df['Pays'].isin(Lmanquant),
       'Stabilité Politique évolution (%)'] = medPer

4 Pays non utilisé(s) ( 4 ) : ['Chine' 'Chine, continentale' 'Nouvelle-Calédonie' 'Polynésie française']

In [276]:
df.describe()

,Année,Part de la viande en protéine (%),Part de la viande en Kcal (%),import-export (milliers de tonnes),Population 2020,Population évolution (%),Stabilité Politique 2020,Stabilité Politique évolution (%)
count,186.0,186.000000,186.000000,186.000000,1.860000e+02,186.000000,186.000000,186.000000
mean,2020.0,8.310484,21.964301,0.129032,4.957317e+07,1.191570,-0.111720,inf
std,0.0,4.796896,10.420491,476.915455,1.836376e+08,1.052419,0.941188,NaN
min,2020.0,0.730000,2.510000,-4042.000000,1.082000e+04,-1.353080,-2.730000,-333.333333
25%,2020.0,4.800000,14.360000,1.000000,2.447730e+06,0.394751,-0.647500,-9.659091
50%,2020.0,7.980000,22.210000,10.000000,9.775375e+06,1.075219,-0.020000,0.480769
75%,2020.0,11.197500,28.180000,39.500000,3.120982e+07,1.930716,0.670000,17.371378
max,2020.0,27.400000,54.420000,1772.000000,1.471287e+09,3.843382,1.490000,inf

On peut voir qu'il y a une valeur infinie

In [277]:
df[df['Stabilité Politique évolution (%)'] == np.inf]

,Pays,Année,Part de la viande en protéine (%),Part de la viande en Kcal (%),id,import-export (milliers de tonnes),Population 2020,Population évolution (%),Stabilité Politique 2020,Stabilité Politique évolution (%)
94,Macédoine du Nord,2020,7.2,18.71,Macédoine du Nord/2020,40.0,2083370.0,-0.00432,0.1,inf

On va supprimer cette ligne

In [278]:
df = df[df['Stabilité Politique évolution (%)'] != np.inf]

In [279]:
df

,Pays,Année,Part de la viande en protéine (%),Part de la viande en Kcal (%),id,import-export (milliers de tonnes),Population 2020,Population évolution (%),Stabilité Politique 2020,Stabilité Politique évolution (%)
0,Afghanistan,2020,2.50,7.52,Afghanistan/2020,36.0,38928350.0,2.330597,-2.73,2.631579
1,Afrique du Sud,2020,11.63,34.21,Afrique du Sud/2020,376.0,59308690.0,1.281493,-0.24,-11.111111
2,Albanie,2020,7.09,15.22,Albanie/2020,26.0,2877800.0,-0.108299,0.08,-27.272727
3,Algérie,2020,2.67,8.10,Algérie/2020,-1.0,43851040.0,1.853504,-0.86,-17.307692
4,Allemagne,2020,9.04,24.85,Allemagne/2020,191.0,83783940.0,0.319576,0.67,17.543860
...,...,...,...,...,...,...,...,...,...,...
181,Émirats arabes unis,2020,6.34,21.70,Émirats arabes unis/2020,407.0,9890400.0,1.226853,0.63,-8.695652
182,Équateur,2020,8.67,26.72,Équateur/2020,0.0,17643050.0,1.550566,-0.36,56.521739
183,États-Unis d'Amérique,2020,14.31,37.02,États-Unis d'Amérique/2020,-3743.0,331002650.0,0.588859,-0.02,-115.384615
184,Éthiopie,2020,1.91,5.09,Éthiopie/2020,1.0,114963590.0,2.573959,-1.74,32.824427
185,Îles Salomon,2020,3.27,9.68,Îles Salomon/2020,5.0,686880.0,2.546953,0.64,25.490196

In [280]:
pibEvo

,Pays,Pib/Habitant ($/habitant) 2019,Pib/Habitant ($/habitant) 2020,PIB évolution (%)
0,Afghanistan,2065.0,1970.6,-4.571429
1,Afrique du Sud,13710.0,12665.8,-7.616338
2,Albanie,13653.2,13253.7,-2.926054
3,Algérie,11522.0,10735.4,-6.826940
4,Allemagne,53929.6,51423.2,-4.647540
...,...,...,...,...
227,Pays à faible revenu et à déficit vivrier,5371.5,5081.4,-5.400726
228,Pays à faible revenu,1945.1,1908.2,-1.897075
229,Pays à revenu moyen,7318.5,6982.4,-4.592471
230,High-income economies,50435.3,47815.6,-5.194179
231,Upper-middle-income economies,19224.5,18165.8,-5.507035

In [281]:
checkUnusedId(df, pibEvo, 'Pays', 'Pays')
checkUnusedId(pibEvo, df, 'Pays', 'Pays')
a = 1

10 Pays non utilisé(s) ( 10 ) : ['Chine, Taiwan Province de' 'Chine, continentale' 'Cuba'
 'Nouvelle-Calédonie' 'Polynésie française' 'République arabe syrienne'
 'République populaire démocratique de Corée' 'Soudan du Sud'
 'Venezuela (République bolivarienne du)' 'Yémen']
57 Pays non utilisé(s) ( 57 ) : ['Bermudes' 'Brunéi Darussalam' 'Guinée équatoriale' 'Îles Marshall'
 'Macédoine du Nord' 'Palaos' 'Palestine' 'Porto Rico' 'Singapour'
 'Somalie' 'Tonga' 'Tuvalu' 'Monde' 'Afrique' 'Afrique orientale'
 'Afrique centrale' 'Afrique septentrionale'
 'Afrique du Nord (Soudan Excl)' 'Afrique australe' 'Afrique occidentale'
 'Afrique subsaharienne' 'Afrique subsaharienne (y compris Soudan)'
 'Amérique du Nord et Europe' 'Amérique septentrionale' 'Europe'
 'Europe orientale' 'Europe septentrionale' 'Europe méridionale'
 'Europe occidentale' 'Amérique latine et Caraïbes' 'Amérique centrale'
 'Caraïbes' 'Amérique du Sud' 'Asie' 'Asie centrale' 'Asie orientale'
 'Asie méridionale' 'Asie du Sud (Inde Excl)' 'Asie du Sud-Est'
 'Asie occidentale' 'Asie centrale et Asie du Sud'
 'Asie orientale et Asie du Sud-Est' 'Asie occidentale et Afrique du Nord'
 'Océanie' 'Australie et Nouvelle-Zélande' 'Mélanésie' 'Micronésie'
 'Polynésie' 'Océanie, hors Australie et Nouvelle-Zélande'
 'Pays les moins développés' 'Pays sans littoral en voie de développement'
 'Petites îles en voie de Développement'
 'Pays à faible revenu et à déficit vivrier' 'Pays à faible revenu'
 'Pays à revenu moyen' 'High-income economies'
 'Upper-middle-income economies']

Encore une fois, on ignore les 56 pays qui apparaissent dans la table PIB mais qui n'apparaissent pas dans la table part car, on n'a pas les données nécessaires sur ces pays pour mener à bien l'analyse. Pour les 10 autres (ceux qui n'apparaissent pas dans la table PIB), on renseigne manuellement les données de la chine et on ignore les autres.

In [282]:
pibChn = pd.read_csv('data\OCDE_PIB_Chine_2018_2020.csv')
pibChn = pibChn[pibChn['LOCATION'] == 'CHN']

pibChnActu = pibChn.loc[pibChn['TIME'] == annee, 'Value'].iloc[0]
pibChnPrec = pibChn.loc[pibChn['TIME'] == (annee-1), 'Value'].iloc[0]
pibChnEvo = 100*(pibChnActu-pibChnPrec)/pibChnPrec
ligne = ['Chine, continentale', pibChnPrec, pibChnActu, pibChnEvo]
pibEvo.loc[len(pibEvo)] = ligne

In [283]:
checkUnusedId(df, pibEvo, 'Pays', 'Pays')
df = pd.merge(df, pibEvo[['Pays', 'Pib/Habitant ($/habitant) ' +
              str(annee), 'PIB évolution (%)']], on='Pays', how='inner')

9 Pays non utilisé(s) ( 9 ) : ['Chine, Taiwan Province de' 'Cuba' 'Nouvelle-Calédonie'
 'Polynésie française' 'République arabe syrienne'
 'République populaire démocratique de Corée' 'Soudan du Sud'
 'Venezuela (République bolivarienne du)' 'Yémen']

In [284]:
df

,Pays,Année,Part de la viande en protéine (%),Part de la viande en Kcal (%),id,import-export (milliers de tonnes),Population 2020,Population évolution (%),Stabilité Politique 2020,Stabilité Politique évolution (%),Pib/Habitant ($/habitant) 2020,PIB évolution (%)
0,Afghanistan,2020,2.50,7.52,Afghanistan/2020,36.0,38928350.0,2.330597,-2.73,2.631579,1970.6,-4.571429
1,Afrique du Sud,2020,11.63,34.21,Afrique du Sud/2020,376.0,59308690.0,1.281493,-0.24,-11.111111,12665.8,-7.616338
2,Albanie,2020,7.09,15.22,Albanie/2020,26.0,2877800.0,-0.108299,0.08,-27.272727,13253.7,-2.926054
3,Algérie,2020,2.67,8.10,Algérie/2020,-1.0,43851040.0,1.853504,-0.86,-17.307692,10735.4,-6.826940
4,Allemagne,2020,9.04,24.85,Allemagne/2020,191.0,83783940.0,0.319576,0.67,17.543860,51423.2,-4.647540
...,...,...,...,...,...,...,...,...,...,...,...,...
171,Émirats arabes unis,2020,6.34,21.70,Émirats arabes unis/2020,407.0,9890400.0,1.226853,0.63,-8.695652,63299.4,-7.272240
172,Équateur,2020,8.67,26.72,Équateur/2020,0.0,17643050.0,1.550566,-0.36,56.521739,10325.0,-9.195645
173,États-Unis d'Amérique,2020,14.31,37.02,États-Unis d'Amérique/2020,-3743.0,331002650.0,0.588859,-0.02,-115.384615,59755.2,-4.328613
174,Éthiopie,2020,1.91,5.09,Éthiopie/2020,1.0,114963590.0,2.573959,-1.74,32.824427,2296.9,3.398758
175,Îles Salomon,2020,3.27,9.68,Îles Salomon/2020,5.0,686880.0,2.546953,0.64,25.490196,2482.4,-6.694230

Ajoutons la production de volailles

In [285]:
checkUnusedId(df, prodVolail, 'Pays', 'Pays')

2 Pays non utilisé(s) ( 2 ) : ['Djibouti' 'Maldives']

['Djibouti', 'Maldives']

On ignore les 2 pays auxquelles on a pas accès à la production

In [286]:
df = pd.merge(df, prodVolail[['Pays', 'Production de Volailles']], on='Pays', how='inner')

In [287]:
df

,Pays,Année,Part de la viande en protéine (%),Part de la viande en Kcal (%),id,import-export (milliers de tonnes),Population 2020,Population évolution (%),Stabilité Politique 2020,Stabilité Politique évolution (%),Pib/Habitant ($/habitant) 2020,PIB évolution (%),Production de Volailles
0,Afghanistan,2020,2.50,7.52,Afghanistan/2020,36.0,38928350.0,2.330597,-2.73,2.631579,1970.6,-4.571429,28
1,Afrique du Sud,2020,11.63,34.21,Afrique du Sud/2020,376.0,59308690.0,1.281493,-0.24,-11.111111,12665.8,-7.616338,1881
2,Albanie,2020,7.09,15.22,Albanie/2020,26.0,2877800.0,-0.108299,0.08,-27.272727,13253.7,-2.926054,14
3,Algérie,2020,2.67,8.10,Algérie/2020,-1.0,43851040.0,1.853504,-0.86,-17.307692,10735.4,-6.826940,284
4,Allemagne,2020,9.04,24.85,Allemagne/2020,191.0,83783940.0,0.319576,0.67,17.543860,51423.2,-4.647540,1572
...,...,...,...,...,...,...,...,...,...,...,...,...,...
169,Émirats arabes unis,2020,6.34,21.70,Émirats arabes unis/2020,407.0,9890400.0,1.226853,0.63,-8.695652,63299.4,-7.272240,51
170,Équateur,2020,8.67,26.72,Équateur/2020,0.0,17643050.0,1.550566,-0.36,56.521739,10325.0,-9.195645,333
171,États-Unis d'Amérique,2020,14.31,37.02,États-Unis d'Amérique/2020,-3743.0,331002650.0,0.588859,-0.02,-115.384615,59755.2,-4.328613,23150
172,Éthiopie,2020,1.91,5.09,Éthiopie/2020,1.0,114963590.0,2.573959,-1.74,32.824427,2296.9,3.398758,68
173,Îles Salomon,2020,3.27,9.68,Îles Salomon/2020,5.0,686880.0,2.546953,0.64,25.490196,2482.4,-6.694230,0

In [288]:
df.describe().round(3)

,Année,Part de la viande en protéine (%),Part de la viande en Kcal (%),import-export (milliers de tonnes),Population 2020,Population évolution (%),Stabilité Politique 2020,Stabilité Politique évolution (%),Pib/Habitant ($/habitant) 2020,PIB évolution (%),Production de Volailles
count,174.0,174.000,174.000,174.000,1.740000e+02,174.000,174.000,174.000,174.000,174.000,174.000
mean,2020.0,8.360,22.100,-5.115,5.211812e+07,1.210,-0.074,16.678,19496.350,-5.745,885.385
std,0.0,4.805,10.405,491.641,1.896098e+08,1.060,0.907,156.393,19479.940,7.591,3123.759
min,2020.0,0.730,2.510,-4042.000,1.082000e+04,-1.353,-2.730,-333.333,731.100,-54.642,0.000
25%,2020.0,4.832,15.160,1.000,2.761168e+06,0.424,-0.638,-11.473,4872.225,-8.306,11.250
50%,2020.0,8.150,22.280,9.500,9.599000e+06,1.085,-0.020,0.966,12642.850,-4.609,72.500
75%,2020.0,11.198,28.118,37.500,3.294546e+07,1.945,0.702,14.123,28184.050,-2.447,348.750
max,2020.0,27.400,54.420,1772.000,1.471287e+09,3.843,1.490,1600.000,112557.000,42.789,23150.000

In [289]:
df.to_parquet('data\Table_Finale.parquet', index=False)

# TEST